Je sobota ráno.
Nad mestom svieti slnko.
Idem dole na ulicu.
Moja suseda, Nina, stojí vonku pred našou budovou.
„Dobré ráno, Maya,“ hovorí a usmieva sa.
„Dobré ráno, Nina,“ odpovedám.
„Dnes mám voľno,“ hovorím jej.
„Vyrážam do mesta.“
„Kam ideš?“ pýta sa Nina.
„Idem dole k vode,“ hovorím.
„Ale nepoznám cestu.“
Nina ukazuje dole ulicou.
„Našťastie je to veľmi jednoduché,“ hovorí.
„Tu choď rovno.“
„A pri parku zaboč doľava.“
„Potom prídeš priamo dole k prístavu.“
„Veľmi pekne ti ďakujem za pomoc, Nina,“ hovorím.
„Niet za čo a šťastnú cestu,“ odpovedá.
Zamávam jej.
Začnem svoju prechádzku smerom k vode.
