Sledujem Nininu trasu.
Vzduch je svieži a chladný.
Teraz kráčam po hlavnej ulici.
Najprv kráčam len rovno.
Na ulici je veľká premávka.
Cestou vidím tri žlté bicykle.
Bicykle rýchlo prechádzajú okolo mňa.
Následne kráčam ďalej vpred.
Potom prídem k veľkému parku.
Teraz si spomínam na Ninine slová.
"Pri parku zaboč doľava," hovorí.
Tu zabočím doľava.
O chvíľu neskôr vidím otvorené dvere.
Je to malá pekáreň.
Je tu krásna vôňa čerstvej kávy.
Milujem teplý chlieb.
Dnes je mesto krásne.
Potom kráčam ďalej smerom k vode.
