Prichádzam na veľké námestie.
Je tu veľa ľudí.
Ale nevidím vodu.
Hľadám prístav.
Vidím staršieho muža na chodníku.
Zastavím ho.
„Prepáčte,“ hovorím.
„Kde je prístav?“
Starší muž prikývne.
Ukáže dopredu.
„Choďte rovno cez námestie,“ hovorí.
„Prejdite okolo múzea.“
„A zabočte doprava.“
Pozriem sa cez námestie.
Vidím veľkú budovu.
Je to múzeum.
„Veľmi pekne ďakujem,“ hovorím.
„Niet za čo,“ odpovedá.
Kráčam ďalej.
