Prechádzam cez veľké námestie.
Zrazu počujem hudbu.
Na rohu stojí pouličný hudobník.
Hrá na gitare.
Počúvam dobrú hudbu.
Dlho sa na neho pozerám.
Potom idem ďalej.
Zabúdam na múzeum.
Zabúdam aj na svoju trasu.
Namiesto toho kráčam úzkou bočnou uličkou.
Je tu veľmi ticho.
Naokolo vidím len nejaké malé domy.
Potom zastanem.
Kde je múzeum?
Teraz sa pozerám okolo seba.
Už ho nevidím.
Rýchlo sa pozriem späť hore ulicou.
Nevidím ani námestie.
Som úplne stratená.
