Stojím na tichej ulici.
Stratila som sa.
Pred sebou vidím mladú ženu.
Venčí malého psa.
Ten pes vyzerá ako pes mojej rodiny, Lola.
Podídem k tej žene.
"Prepáčte," hovorím.
"Hľadám prístav."
Žena zastane a počúva.
Ukáže naspäť hore ulicou.
"Choďte rovno späť na námestie," hovorí.
"A pri múzeu odbočte doprava."
"Veľmi pekne ďakujem za pomoc," hovorím.
"Niet za čo," odpovedá žena.
Pozriem sa dole na malého psa.
Pozerá sa na mňa.
Idem späť smerom k námestiu.
Teraz viem, kde som.
