Kráčam späť po tichej ulici.
Idem rovno.
Čoskoro opäť vidím to veľké námestie.
Potom prechádzam cez námestie.
Teraz stojím pri múzeu.
Pamätám si slová tej ženy: „Odbočte doprava.“
Pri múzeu odbočím doprava.
Kráčam dolu širokou ulicou.
Pozerám sa dopredu.
Konečne vidím niečo modré.
Je to voda!
Cestou idem okolo malej kaviarne.
Nakoniec idem až úplne dole k vode.
Teraz som v prístave.
Prístav je veľmi veľký.
Vietor je chladný a svieži.
Na vode je veľa lodí.
Tu sa zastavím.
Stojím a pozerám sa na lode.
