Kráčam rovno popri prístave.
Prechádzam okolo malých člnov.
Zrazu vidím veľa ľudí.
Stoja dole pri vode.
Idem tam.
Konečne ju vidím.
Malá morská panna sedí na kameni vo vode.
Je to veľmi slávna socha v Kodani.
Tá postava v skutočnosti nie je veľmi veľká.
Ale bronzová postava je na slnku krásna.
Stojím medzi ostatnými návštevníkmi.
Veľa turistov si fotí sochu.
Aj ja si vyťahujem telefón.
Robím krásnu fotku morskej panny.
Posielam fotku svojej rodine do Mexika.
Moja sestra Sofía rýchlo odpovedá.
„Je veľmi pekná,“ píše.
Znova sa pozerám na vodu.
