Je neskoro popoludní.
Teraz idem domov do svojho bytu.
Idem jednoduchou cestou.
Len idem po tej dlhej ceste.
Cesta je úplne rovná.
Idem popri vode.
Nakoniec odbočím od vody.
Teraz idem opäť do mesta.
Potom idem okolo pekárne.
Stále to vonia kávou.
O niečo neskôr vidím park.
Pri parku odbočím doprava.
Nikoho sa nepýtam na cestu.
Cestu nájdem úplne sama.
O niečo neskôr vidím svoju vlastnú ulicu.
Nakoniec stojím pri svojich vchodových dverách.
Od dverí sa pozerám späť dole ulicou.
Teraz poznám svoju cestu domov.
