Dnes si musím vyzdvihnúť balík.
Je na druhej strane mesta.
Pozerám sa na svoj telefón.
Otváram aplikáciu verejnej dopravy.
Plánujem si trasu.
Trasa je dlhá.
Má tri časti.
Najprv musím ísť autobusom.
Autobus ide k metru.
Potom musím ísť metrom.
Nakoniec musím ísť do prístavu.
Tu musím ísť prístavným autobusom.
Prístavný autobus je veľká loď.
Plaví sa po vode.
Balík je v malom obchode.
Obchod sa nachádza blízko vody.
Je to dobrý plán.
Beriem si svoju modrú cestovnú kartu.
Som pripravená na cestu.
