Kráčam k automatu na lístky na ulici.
Najprv moja cestovná karta potrebuje viac peňazí.
Vyberiem svoju cestovnú kartu z tašky.
Je to malá modrá karta.
Položím kartu na obrazovku automatu.
Obrazovka ukazuje môj zostatok.
Zostatok je príliš nízky na dlhú cestu.
Ťuknem na obrazovku.
Vyberiem si sumu.
Zaplatím dvesto korún svojou platobnou kartou.
Automat na obrazovke vypíše „Schválené“.
Teraz mám na karte peniaze.
Dám kartu späť do tašky.
Som pripravená na dlhú cestu.
Teraz musím ísť autobusom.
Prejdem k autobusovej zastávke.
