Stojím na autobusovej zastávke.
Čoskoro pôjdem autobusom.
Pozerám sa dolu ulicou.
Po piatich minútach prichádza autobus.
Je to dlhý a žltý autobus.
Autobus zastavuje priamo predo mnou.
Dvere sa otvárajú.
Nastupujem do autobusu.
V ruke mám svoju cestovnú kartu.
Skenujem kartu pri dverách.
Dnes je tu veľa cestujúcich.
Hľadám si voľné miesto.
Nachádzam dobré miesto pri okne.
Sadám si.
Pozerám sa von na mesto.
Teraz idem autobusom na stanicu metra.
