Autobus zastavuje na rušnom námestí.
Vystupujem z autobusu.
Lúčim sa so staršou paňou.
Teraz idem na metro.
Prechádzam cez námestie.
Je tu veľa ľudí.
Idem dole širokými schodmi.
Stanica je v podzemí.
Je veľmi veľká a svetlá.
Musím sa znova zaevidovať.
Vyťahujem svoju modrú kartu.
Skenujem kartu na prístroji.
Prístroj vydá hlasné pípnutie.
Teraz môžem cestovať metrom.
Idem dole na nástupište.
Idem ďalším vlakom.
Ide priamo k prístavu.
Vlak príde o tri minúty.
