Metro prichádza a dvere sa otvárajú.
Vchádzam do vlaku.
Vlak jazdí bez vodiča.
Idem úplne dopredu.
Stojím pri veľkom okne.
Cestujem metrom cez tmu.
Sme v dlhom tuneli.
Ideme veľmi rýchlo.
Svetlo letí okolo okna.
Vyzerá to fantasticky.
Vedľa mňa stojí malý chlapec.
Aj on sa pozerá von do tmy.
Často cestujem metrom.
Je to rýchla a jednoduchá cesta.
Teraz sa blížime k mojej stanici.
Idem do prístavu.
Moja ďalšia cesta je prístavným autobusom.
Teším sa, že uvidím vodu.
