Cesta metrom sa skončila.
Teraz idem hore na ulicu.
Idem eskalátorom.
Hore na ulici svieti slnko.
Teraz idem k vode.
Idem prístavným autobusom.
Kráčam dolu širokou ulicou.
Potom uvidím kanál.
Voda je veľmi modrá.
Hľadám svoju zastávku.
Kde zastavuje loď?
Podídem bližšie k okraju.
Potom uvidím malé drevené mólo.
Nachádza sa úplne dole pri vode.
Pri móle je žltá tabuľa.
Na tabuli je napísané „Prístavný autobus“.
Toto je to správne miesto.
Vyjdem na mólo.
Teraz už len čakám na loď.
