Široká loď prichádza po vode.
Je to prístavný autobus.
Loď pripláva k drevenému mólu.
Zastavuje na okraji.
Teraz idem prístavným autobusom.
Nastupujem na palubu lode.
Znovu si skenujem modrú cestovnú kartu.
Vnútri sedí veľa cestujúcich.
Ale ja vychádzam na otvorenú palubu.
Stojím úplne vpredu.
Plavíme sa loďou po modrej vode.
Mesto vyzerá z vody krásne.
Slnko na nás svieti.
Zhlboka sa nadýchnem.
Vzduch je veľmi svieži a studený.
Užívam si krátku cestu.
Čoskoro sme na druhej strane.
