Loď prichádza na druhý breh.
Prístavný autobus zastavuje pri malom móle.
Vystupujem z lode.
Cesta loďou sa teraz skončila.
Kontrolujem mapu v telefóne.
Idem do malého kiosku.
Kiosk sa nachádza tam na rohu.
Kráčam hore ulicou.
Na konci cesty vidím obchod.
Otváram dvere a vchádzam dnu.
Za pokladňou stojí mladý muž.
„Ahoj,“ hovorí prívetivo.
„Ahoj, idem si vyzdvihnúť balík,“ hovorím.
Muž prikývne a usmeje sa.
Pýta sa na moje meno.
„Moje meno je Maya,“ odpovedám.
Na polici nájde veľkú škatuľu.
Dáva mi balík.
„Veľmi pekne ďakujem za pomoc,“ hovorím.
Teraz sa so svojím balíkom opäť vydávam na dlhú cestu domov.
