V Kodani je konečne jar.
Podídem k oknu v mojej obývačke.
Otvorím ho a cítim teplý vánok.
Vzduch je dnes večer svieži a mierny.
Večery sú teraz zrazu oveľa svetlejšie.
Slnko stále svieti na môj stôl.
Sadnem si na svoju stoličku.
Vyberiem si svoj cestovateľský denník a modré pero.
Veľmi rada píšem o svojich zážitkoch v Dánsku.
Otvorím knihu na prázdnej strane.
Myslím na svoj fantastický víkend.
Včera som bola na dlhom výlete.
Cestovala som úplne sama do Odense.
Bol to môj prvý výlet mimo Kodane.
Usmievam sa, pretože som mala naozaj dobrý deň.
Teraz si to chcem všetko zapísať.
Priložím pero na papier a začnem svoj príbeh.
