Napísala som do denníka o svojom výlete do Odense.
Bolo to krásne sobotné ráno.
Zobudila som sa skoro, o siedmej.
Slnko svietilo a obloha bola modrá.
Zbalila som si svoj malý zelený batoh.
Do tašky som si dala zápisník a fotoaparát.
Vzala som si aj hrubý sveter.
Jarné počasie v Dánsku môže byť trochu chladné.
Potom som išla autobusom na veľkú stanicu v Kodani.
Vnútri bolo veľa uponáhľaných ľudí.
Podišla som k malému kiosku.
Kúpila som si veľkú teplú kávu na cestu.
Stála štyridsaťpäť korún.
Pozrela som sa hore na veľkú obrazovku.
Rýchlo som na obrazovke našla svoj vlak.
Mala som ísť rýchlym vlakom do Odense.
Vlak dorazil na nástupište presne o ôsmej.
Vošla som do vlaku a našla si miesto pri veľkom okne.
Pila som svoju teplú kávu a tešila sa na výlet.
