Sedela som na svojom sedadle vo vlaku a obzerala sa navôkol.
Oproti mne sedel otec.
Mal so sebou svoje dve malé deti.
Otec mal veľkú knihu.
Veľmi si chcel čítať svoju knihu.
Ale nemal veľa pokoja.
Jeho dcéra mala červenú loptu.
Jeho syn mal zelené hračkárske auto.
Deti vôbec nesedeli pokojne.
Neustále hádzali svoje hračky na podlahu.
Otec si hlasno povzdychol a zavrel svoju knihu.
Zdvihol veci z podlahy.
Vrátil deťom ich hračky.
„Musíte sedieť ticho,“ povedal unavene.
Znovu otvoril svoju knihu.
O dve minúty neskôr lopta spadla na podlahu.
Trafila otcovu ľavú topánku.
Muž opäť zdvihol loptu.
Usmiala som sa na unaveného otca.
Iba pokrútil hlavou a pozrel sa dole do svojej knihy.
