Rodina mala so sebou vo vlaku aj malého psa.
Bol veľmi roztomilý, ale nebol ticho.
Pes ležal vo svojom malom košíku na podlahe.
Otec sa opäť pozrel dole na svoju knihu.
Chcel si len trochu čítať.
Ale zrazu pes vyskočil zo svojho košíka.
Rýchlo pribehol k otcovi.
Sedel s jednou nohou vyloženou na taške.
Pes mu schmatol ľavú topánku.
Vzal topánku do papule.
Potom rýchlo utiekol.
"Nie, vráť sa s mojou topánkou!" zakričal otec.
Postavil sa v ponožkách.
Rozbehol sa za psom dole uličkou.
Tie dve deti naňho ukázali.
Pozreli sa na seba a nahlas sa smiali.
Pozerala som sa na ne zo svojho miesta.
Aj ja som sa trochu zasmiala za svojou knihou.
Našťastie napokon svojho psa chytil.
Dostal späť aj svoju topánku.
