Pokračovala som dolu úzkou ulicou.
Zastavila som sa pred veľmi starým domom.
Starší manželský pár bol vonku na jarnom slnku.
Muž stál vo svojej záhrade.
Maľoval svoj starý plot štetcom.
Nová farba bola svetložltá.
Jeho manželka sedela neďaleko na drevenej lavičke.
Oddychovala a pila svoj teplý čaj.
Muž ma uvidel a na chvíľu sa zastavil.
Priateľsky zamával štetcom.
„Dobré ráno!“ povedal mi.
„Vaša záhrada vyzerá krásne,“ povedala som.
Jeho manželka sa na mňa usmiala zo svojej lavičky.
„Ďakujem, užívame si jar,“ odpovedala.
Muž pokojne ďalej maľoval svoj plot.
V ich záhrade spievali vtáky.
Radostne som pokračovala vo svojej prechádzke.
