Potom som išla do veľkého mestského múzea.
Bolo o slávnom spisovateľovi Hansovi Christianovi Andersenovi.
Kúpila som si lístok a vošla som do tej krásnej budovy.
Výstava rozprávala o jeho živote a jeho dlhých cestách.
Pozerala som si jeho staré veci vo veľkej sklenenej vitríne.
Všade si so sebou bral svoj vysoký klobúk.
Ten vysoký čierny klobúk ležal priamo tam predo mnou.
Ležal tam aj jeho papier a jeho staré pero.
Používal ich, keď písal svoje fantastické rozprávky.
Prečítala som si dlhý text na bielej stene.
Bol o mužovi, ktorý stál za mojou obľúbenou rozprávkou.
Bol to totiž on, kto stvoril malú morskú vílu.
Stretla som ju ako sochu v Kodani ešte vo februári.
Bolo zábavné vidieť teraz spisovateľove vlastné veci.
Urobila som zopár fotiek jeho veľkej cestovnej tašky.
Očividne miloval navštevovať nové krajiny.
Nakoniec som si v obchode múzea kúpila malú knihu.
Obsahovala všetky jeho najlepšie príbehy.
Teraz mám pocit, že poznám dánsku kultúru o niečo lepšie.
