Stále sedím pri svojom stole v obývačke v Kodani.
Píšem posledné slová do svojho denníka.
Potom položím pero na stôl.
Zatvorím malú knihu a usmejem sa.
Bol to úplne perfektný víkend v Odense.
Spomínam na svoj dobrý výlet.
Pamätám si starého muža, ktorý maľoval svoj plot.
Pamätám si aj vystresovaného otca a jeho dve živé deti vo vlaku.
Trochu sa sama pre seba smejem.
Pozerám sa von zo svojho otvoreného okna.
Večer je neuveriteľne dlhý a svetlý.
Slnko pomaly zapadá nad mestom.
Veľmi pomaly sa stmieva.
Milujem svoju prvú jar v Dánsku.
Zajtra sa začína nový týždeň.
Musím skoro vstať a ísť autobusom do práce.
Ale dnes večer mám veľa času.
Postavím sa a idem do kuchyne.
Prinesiem si pohár studenej vody.
Som pripravená na pondelok.
