Je piatok večer a Nina klope na moje dvere.
Má so sebou svojho psa Ludwiga.
Cez víkend zostane u mňa.
Nina sa usmieva a podáva mi vôdzku.
"Veľmi pekne ti ďakujem za pomoc, Maya," hovorí.
"To je úplne v poriadku," odpovedám veselo.
Vysvetľuje mi o ňom zopár vecí.
"Dávaj mu jedlo o siedmej ráno a o šiestej večer," hovorí Nina.
"A pamätaj, nesmie dostať ľudské jedlo."
Smejem sa a pozerám sa dole na malého psa.
"Nie, Ludwig, moja večera nie je pre teba," hovorím mu.
Nina sa tiež smeje a ukazuje na dvere.
"Vždy ho maj na vôdzke, keď pôjdete blízko veľkej cesty," hovorí.
"V parku môže behať voľne."
Prikývnem.
"Neboj sa, dobre sa o neho postarám."
Nina ma objíma a lúči sa s nami.
Zatvára dvere a ja stojím sama s Ludwigom.
Pozerá sa na mňa a vrtí chvostom.
Už teraz ho mám veľmi rada.
