Je neskorý piatkový večer.
Predtým, ako pôjdeme spať, zoberiem Ludwiga von.
Ideme na krátku prechádzku po okolí.
Ulice sú teraz veľmi tiché.
Ludwig kráča pekne vedľa mňa.
Zrazu sa zastaví.
Dychtivo oňucháva niečo na chodníku.
Je to špinavá taška so zvyškami jedla.
Otvorí papuľu, aby to zobral.
„Nie, pusť to!“ poviem mu rázne.
Jemne ho odtiahnem od tašky.
„Odpadky nie sú jedlo, Ludwig,“ vysvetľujem.
„Poď sem, Ludwig,“ zavolám na neho.
Pustí tašku a pozrie sa na mňa.
Rýchlo začne vrteť chvostom.
„Dobrý psík,“ poviem a pohladkám ho.
Pokračujeme v prechádzke po ulici.
Teraz už len musíme ísť domov a spať.
