Po raňajkách mám veľa času.
Zvyčajne v sobotu pracujem ako dobrovoľníčka v kaviarni.
Ale Ludwig by nemal byť sám.
Dnes mám našťastie v kaviarni voľno.
Dohodla som sa s nimi minulý týždeň.
Teraz máme s Ludwigom celé ráno pre seba.
Ideme von na dvor za mojou budovou.
Vytiahnem jeho malú loptičku.
„Pozri na loptičku, Ludwig!“ poviem mu.
Hodím ju cez trávu.
„Prines ju!“ zakričím.
Rýchlo beží a chytí loptičku.
„Poď sem!“ zavolám.
Radostne beží späť ku mne.
„Daj mi ju,“ poviem jemne.
Pustí loptičku a ja ho pohladkám.
„Si dobrý pes,“ poviem a usmejem sa.
Znova ju hodím a on ju prinesie.
Musím sa o neho dobre starať celý víkend.
Som veľmi rada, že som s ním zostala doma.
