Ludwig radostne behá po lese.
Zrazu zbadá veľkého vtáka.
Rýchlo beží za ním.
Beží úplne až k stromom.
"Stoj, Ludwig!" kričím nahlas.
"Poď sem!"
Z vrecka vytiahnem malú maškrtu.
Čupnem si do trávy.
"Ludwig, pozri sem," zavolám jemne.
Zastaví sa a pozrie na mňa.
Veľmi chce tú maškrtu.
Rýchlo beží späť ku mne.
"Sadni," poviem pokojne.
Sadne si a ja mu ju dám.
"Dobrý psík," poviem a pohladím ho.
Znova mu pripnem vôdzku.
Teraz musíme ísť domov a oddýchnuť si.
