Je nedeľa popoludní a niekto klope na dvere.
Ludwig vybehne na chodbu a radostne šteká.
Otvorím dvere a vonku stojí Nina so svojou víkendovou taškou.
„Ahoj, Maya, veľmi pekne ďakujem za pomoc,“ hovorí a usmieva sa.
Vrtí chvostom a vyskakuje na ňu.
„Dolu, Ludwig,“ hovorí Nina a pohladká ho.
„Bol to naozaj dobrý pes,“ hovorím jej.
Nina sa smeje a berie jeho vôdzku z malého stolíka.
„Išla si s ním na prechádzku do psieho lesa?“ pýta sa.
„Áno, a veľmi sa mu to páčilo,“ odpovedám.
Dávam jej zvyšok psieho krmiva.
„Nech sa páči, tu je zvyšok.“
„Niekedy ho veľmi rada opäť postrážim.“
„Jasné,“ hovorí Nina.
„Poď, Ludwig, musíme ísť domov,“ hovorí Nina psovi.
Mávam im obom na rozlúčku.
V byte je bez neho zrazu veľmi ticho.
