Každý štvrtok večer hrám bedminton.
Kasper a Sara hrajú v rovnakom tíme ako ja.
Zajtra je piatok a pozvala som ich na večeru.
Chcem uvariť tradičné dánske jedlo.
Tak sa rozhodnem pripraviť fašírky so zemiakmi.
Nájdem dobrý recept na internete.
Teraz musím napísať nákupný zoznam.
Najprv potrebujem mäso na fašírky.
V recepte sa píše päťsto gramov mletého bravčového mäsa.
Potom potrebujem aj dve veľké žlté cibule.
Poznačím si aj trochu mlieka a jedno vajce.
Všetko si to zapíšem do poznámkového bloku.
Potom sa pozriem na množstvo zemiakov.
Musím kúpiť presne jedno kilo malých zemiakov.
Nakoniec do zoznamu pridám maslo a soľ.
Na opekanie mäsa treba vždy použiť dostatok masla.
Zoznam je konečne hotový a ja som pripravená.
Zajtra po práci pôjdem priamo do supermarketu.
