Stojím v supermarkete po práci.
Dnes je v obchode veľa ľudí.
V ruke mám svoj nákupný zoznam.
Na zajtrajšiu večeru potrebujem presné množstvá.
Najprv idem k zelenine.
Nájdem nejaké malé, dobré zemiaky.
Dám ich do vrecka a odvážim ich.
Váha ukazuje presne jedno kilo.
To je to správne množstvo do receptu.
Potom vezmem dve veľké, žlté cibule.
Následne prejdem k mäsu.
Potrebujem mleté bravčové mäso na fašírky.
Pozerám sa na rôzne balenia v chladiacom boxe.
Vyberiem si balenie s päťsto gramami.
Nakoniec si svoj zoznam skontrolujem ešte raz.
Zoberiem si aj balenie masla a trochu mlieka.
Všetky veci vložím do košíka.
Teraz som pripravená variť pre Kaspera a Saru.
