Som doma vo svojej kuchyni.
Dávam si zásteru.
Čítam si recept na telefóne.
Recept je veľmi zrozumiteľný.
Píše sa tam: Najprv nakrájajte cibuľu veľmi najemno.
Potom dajte mäso do veľkej misy.
Následne pridajte vajce, trochu múky a mlieka.
Nakoniec to všetko dôkladne zmiešajte.
Nájdem si dosku na krájanie a ostrý nôž.
Nakrájam tie dve žlté cibule na malé kúsky.
Trochu mi slzia oči.
Otvorím balenie s päťsto gramami mletého bravčového mäsa.
Dám mäso do svojej veľkej modrej misy.
Potom dám cibuľu k mäsu.
Rozbijem vajce do misy.
Následne pridám trochu múky a mlieka.
Vezmem veľkú lyžicu a všetko to spolu zamiešam.
Mäsová zmes vyzerá naozaj dobre.
Prvý krok bol veľmi jednoduchý.
