Teraz musím uvariť zemiaky.
Znova sa pozriem na svoj recept.
Má nejaké veľmi krátke pokyny.
Najprv sa tam píše: „Vydrhnite malé zemiaky dočista.“
Robím to malou kefkou pod studenou vodou.
Potom si prečítam ďalší riadok.
Ďalej sa tam píše: „Vložte zemiaky do hrnca s vodou.“
Vyberiem zo skrinky svoj veľký hrniec.
Vložím celé kilo do hrnca.
Hrniec je takmer úplne plný.
Aký je ďalší krok?
V recepte sa píše: „Pridajte do vody veľkú lyžicu hrubej soli.“
Vezmem si soľ a lyžicu.
Nasypem soľ na lyžicu.
Pridám tú veľkú lyžicu k zemiakom.
Nakoniec sa tam píše: „Zapnite sporák.“
Položím hrniec na sporák a zapnem ho.
Teraz sa zemiaky musia variť už len dvadsať minút.
