Zemiaky sa teraz varia v hrnci.
V kuchyni to už krásne vonia.
Vyberiem veľkú panvicu.
Čítam si ďalšie pokyny v recepte.
Ďalšia časť je dôležitá.
Píše sa tam: "Najprv na panvici roztopte hrubý kúsok masla."
Odkrojím trochu masla a dám ho na panvicu.
Maslo rýchlo zasyčí na horúcom kove.
Čítam ďalej: "Potom z mäsa vytvarujte okrúhle guľky."
Na tvarovanie mäsa používam lyžicu.
Je to trochu ťažké, ale sú pekné a okrúhle.
Opatrne ich ukladám na horúcu panvicu.
Recept pokračuje: "Potom ich opekajte, kým nebudú chrumkavé a hnedé."
Trochu znížim teplotu.
Musia sa opekať asi pätnásť minút.
Často ich otáčam, aby neprihoreli.
Fantasticky voňajú a dostávajú dobrú farbu.
Teraz sú mäsové guľky a zemiaky takmer hotové.
Teším sa, keď prídu Kasper a Sara.
Je to úplne perfektné načasovanie.
