Zatiaľ čo sa mäso dopeká, prestieram stôl v obývačke.
Môj jedálenský kút je dosť malý.
Ale je tu dosť miesta pre Kaspera, Saru a mňa.
Zo skrinky vyberám tri taniere.
Ukladám ich na malý stôl.
Potom otváram zásuvku s príborom.
Vyberám vidličky a nože.
Ku každému tanieru ukladám vidličku a nôž.
Budeme potrebovať aj tri poháre na vodu.
Idem po ne do kuchyne.
Nakoniec z balíka vyberám niekoľko svetlomodrých papierových servítok.
Pekne ich skladám.
Potom na každý tanier ukladám servítku.
Teraz je stôl prestretý a pripravený pre hostí.
Vraciam sa k sporáku.
Fašírky ešte stále prskajú na horúcej panvici.
Odstavujem panvicu z ohňa.
Som úplne pripravená na hostí.
