Zvoní zvonček.
S úsmevom otváram dvere.
Vonku stoja Kasper a Sara.
Usmievajú sa a kývajú mi.
"Ahoj Maya, a veľmi pekne ďakujeme za pozvanie!" hovorí radostne Kasper.
"Ahoj!"
"Poďte dnu," odpovedám.
"Už teraz to úžasne vonia," hovorí Sara.
"Najprv si vyzlečte bundy," hovorím im.
Vezmem ich bundy a zavesím ich na chodbe.
Potom mi Sara podá tašku.
"Priniesli sme nejaké studené pivá," vysvetľuje.
"Je to miestne dánske pivo," dodáva Kasper.
Pozriem sa do tašky.
Je v nej šesť fliaš.
"Veľmi pekne ďakujem, to je úplne perfektné," hovorím.
"Hneď ich dám do chladničky."
"Dobrý nápad, a potom sme pripravení jesť," smeje sa Kasper.
Idem s fľašami do kuchyne.
