Všetci traja sme teraz veľmi sýti.
Na stole už nezostalo žiadne jedlo.
„To bola fantastická večera, Maya,“ hovorí šťastne Sara.
„Ako presne sa robia tieto fašírky?“ pýta sa potom.
„Je to veľmi ťažké?“
„Nie, v skutočnosti je to celkom ľahké,“ odpovedám.
„Najprv sa nakrája cibuľa a potom sa primieša mäso,“ vysvetľujem.
„V telefóne mám naozaj dobrý recept.“
„Dnes večer ti pošlem link.“
„Veľmi pekne ďakujem, to by som rada skúsila,“ hovorí Sara.
Postavíme sa z malých stoličiek.
Kasper začína zbierať prázdne taniere.
„Máme teraz odniesť taniere do kuchyne?“ pýta sa.
„Áno, prosím.“
„Len ich polož na kuchynskú linku,“ hovorím.
Rýchlo spoločne odpraceme zo stola.
„Ale hej, nabudúce som na rade ja,“ hovorí zrazu Kasper.
„Áno.“
„Nabudúce nám musíš navariť ty!“
Sara sa smeje.
„Presne tak.“
„A sľubujem, že to bude dobré,“ hovorí.
Smejeme sa a odnášame zvyšok vecí do kuchyne.
