Je dvanásť hodín a v kaviarni som skončila.
Moja dobrovoľnícka zmena v sobotu dopoludnia je vždy rušná, ale príjemná.
Teraz mám voľno.
Počasie je dnes krásne.
Už je naozaj príjemne a krásne.
Slnko svieti a je oveľa teplejšie ako minulý týždeň.
Mám chuť sa trochu rozmaznávať.
Kráčam po veľkej pešej zóne.
Dnes je v meste veľmi veľa ľudí.
Ľudia sa usmievajú a užívajú si pekné počasie.
Rada by som si kúpila nejaké nové oblečenie.
Hľadám nejaké ľahšie jarné oblečenie.
Možno peknú novú jarnú bundu a košeľu.
Pozerám sa cez výklad veľkého obchodu s oblečením.
Majú oblečenie v mnohých krásnych jarných farbách.
Rozhodnem sa vojsť dnu.
Teším sa, že si niektoré z tých vecí vyskúšam.
