Vchádzam do veľkého obchodu s oblečením.
Prezerám si nové jarné oblečenie.
Visí tam veľa ľahkých búnd a košieľ.
Pomaly sa obzerám po obchode.
Všetko vyzerá sviežo a jarne.
Zrazu zbadám veľmi peknú bundu.
Je svetlozelená.
Zvesím ju z vešiaka.
Rada by som si ju vyskúšala.
Na podlahe stojí veľké zrkadlo.
Takže nepotrebujem skúšobnú kabínku.
Oblečiem si tú svetlozelenú bundu.
Pozerám sa na seba v zrkadle.
Bunda mi veľmi dobre sedí.
Nie je príliš veľká a nie je príliš malá.
Vlastne mi sedí perfektne.
Aj farba na mne vyzerá pekne.
Usmievam sa do zrkadla.
Bundu si znova vyzlečiem.
Rozhodnem sa ju kúpiť.
