Kráčam smerom k pokladni so svojou novou bundou.
Po ceste vidím veľmi peknú košeľu.
Je svetlomodrá a vyrobená z mäkkej bavlny.
Vlastne potrebujem novú košeľu do kancelárie.
Zvesím košeľu z vešiaka.
Pozriem sa smerom k skúšobným kabínkam.
Dnes je v obchode veľa ľudí.
Rad do skúšobných kabínok je veľmi dlhý.
Nechcem dlho čakať.
Preto sa rozhodnem, že si ju najprv nevyskúšam.
Zvyčajne nosím veľkosť M.
Skontrolujem veľkosť košele.
Myslím si však, že vyzerá byť trochu malá.
Ale väčšia veľkosť je asi príliš veľká.
A menšia veľkosť bude určite príliš tesná.
Takže si jednoducho vezmem svoju bežnú veľkosť.
Prehodím si košeľu cez ruku spolu s bundou.
Dúfam, že mi košeľa doma sadne.
