Idem k pokladni so svojimi novými vecami.
Predavačka zdvihne zrak a pozdraví.
„Dobrý deň,“ povie.
„Dobrý deň,“ odpoviem.
Položím svetlozelenú bundu a modrú košeľu na pult.
Naskenuje obe veci.
„Bude to šesťstopäťdesiat kroner,“ povie.
Zaplatím kartou.
„Chcete bloček?“ opýta sa predavačka.
„Áno, prosím,“ odpoviem rýchlo.
„Neskúšala som si tú košeľu,“ vysvetlím.
„Dúfam, že nebudem potrebovať väčšiu.“
„Vždy si ju môžete vymeniť,“ povie predavačka milo.
Vytlačí bloček a podá mi ho.
„Nezabudnite si ho odložiť,“ povie.
Vezmem si bloček.
Zložím ten malý kúsok papiera.
Potom si ho bezpečne vložím do peňaženky.
„Prajem pekný víkend,“ poviem jej.
„Aj vám,“ odpovie.
