Neskôr popoludní som späť vo svojom byte.
Som trochu unavená po nákupoch.
Sadnem si na posteľ a vybaľujem svoje tašky.
Najprv vyberiem svoju novú, svetlozelenú jarnú bundu.
Potom vyberiem modrú bavlnenú košeľu.
Teším sa, ako si ju vyskúšam.
Vyzlečiem si svoj starý sveter a oblečiem si košeľu.
Ale hneď cítim problém.
Košeľa je až príliš malá.
Cez ramená je veľmi tesná.
Vlastne ledva môžem zdvihnúť ruky.
V zrkadle vyzerá košeľa až príliš tesná.
Očividne potrebujem väčšiu veľkosť.
Tento model je oveľa menší ako moja bežná veľkosť.
Je trochu škoda, že som si ju nevyskúšala v obchode.
Ale rad do skúšobných kabínok bol jednoducho príliš dlhý.
Malú košeľu si opäť vyzlečiem.
Pekne ju poskladám a dám ju späť do tašky.
Našťastie mám stále svoju účtenku.
Môžem košeľu vymeniť za väčšiu, keď v pondelok skončím v práci.
