Je pondelok popoludní a ja už mám po práci.
Idem autobusom od softvérovej spoločnosti.
Ale neidem priamo domov.
Vystupujem z autobusu pri veľkej pešej zóne.
Idem k obchodu s oblečením zo soboty.
V taške mám tú modrú bavlnenú košeľu.
Je stále úplne nová a nenosená.
Košeľa je príliš malá, takže by som si chcela vyskúšať väčšiu.
Dúfam, že ju majú v inej veľkosti.
Vchádzam do svetlého obchodu.
Idem priamo k pokladni.
Otvorím peňaženku a nájdem svoj bloček.
Držím ho pripravený v ruke.
Potom z tašky vyberiem košeľu.
Za pultom stojí priateľská predavačka.
Zdvihne zrak a usmeje sa na mňa.
Opätujem jej úsmev.
