Položím košeľu a bloček na pult.
Predavačka je pripravená mi pomôcť.
"Dobrý deň, v sobotu som kúpila túto košeľu," hovorím.
"Ale bohužiaľ je príliš malá."
"Môžem ju vymeniť za väčšiu veľkosť?"
"Áno, samozrejme, že môžete," odpovedá predavačka.
"Akú veľkosť potrebujete?"
"Potrebujem veľkosť L namiesto M," vysvetľujem.
"Moment," hovorí predavačka.
Prejde k regálom s modrými košeľami.
Rýchlo nájde správnu veľkosť a vráti sa.
"Tu je veľkosť L," hovorí s úsmevom.
"Chcete si ju najprv vyskúšať?"
"Áno, prosím," odpovedám radostne.
"Skúšobné kabínky sú hneď tamto napravo," hovorí mi.
"Veľmi pekne ďakujem za pomoc," hovorím a beriem si novú košeľu.
Teraz uvidím, či je tá väčšia košeľa lepšia.
