Je tichý utorkový večer v mojom byte.
Upratujem svoj malý kuchynský stôl.
Taniere sú umyté a stôl je utretý.
Užívam si pokoj po dlhom dni v kancelárii.
Ale zrazu si spomeniem na dôležitú úlohu.
Musím si aktualizovať kontaktné údaje na webovej stránke môjho dodávateľa elektriny.
Dostala som od nich e-mail s pripomienkou.
V správe sa píše: "Vaše údaje musia byť aktualizované do stredy."
To je predsa už zajtra!
Je to naozaj nudná digitálna povinnosť.
Zvyčajne takéto veci odkladám na poslednú chvíľu.
Vlastne sa na to často úplne zabudne, kým nedostanem varovanie.
Ale dnes večer chcem byť v predstihu.
Chvíľu sa pozerám na prázdny stôl.
Môj počítač je v pracovnej taške vonku na chodbe.
Teraz nemám vôbec energiu ísť ho zobrať a zapnúť.
Našťastie na malé úlohy zvyčajne používam len svoj telefón.
S ťažkým povzdychom vyberám telefón z vrecka.
Teraz to už len treba mať za sebou.
