Položím si telefón na stôl a relaxujem.
Zrazu sa ozve rýchle zaklopanie na moje dvere.
Preruší to moje myšlienky.
Postavím sa z pohovky a vyjdem do predsiene.
Keď otvorím dvere, vonku na chodbe stojí Nina.
V rukách má malú kartónovú škatuľu.
„Ahoj Maya, mám pre teba balík,“ hovorí a usmieva sa.
Podáva mi škatuľu.
„Doručili ho ku mne skôr popoludní,“ vysvetľuje Nina.
„Poštár si asi omylom pomýlil naše dvere.“
Pozriem sa na škatuľu a vidím na nej svoje meno.
„Och!“
„To sú moje nové kávové zrná!“
„Zvyčajne si ich kupujem na internete,“ hovorím jej.
„Normálne sa balíky nechávajú dole vo vchode,“ hovorí Nina.
„Áno, zvyčajne ich dávajú tam,“ odpovedám.
S veľkým úsmevom si prevezmem kartónovú škatuľu.
Už teraz jemne vonia po praženej káve.
„Veľmi pekne ďakujem, že si mi ju priniesla,“ hovorím.
