Zatváram dvere za Ninou.
Pre dnešný večer som s obrazovkami úplne skončila.
Dávam telefón na nabíjačku.
Zvyčajne leží na gauči, ale teraz sa musí nabiť.
Zajtra je streda.
V stredu večer zvyčajne cvičím vo fitnescentre.
Mojím vlastným malým pravidlom je, že športová taška sa balí večer vopred.
Najprv sa taška vezme zo skrine na chodbe.
Potom sa do nej vložia moje topánky.
Nájdem si aj fľašu na vodu v kuchyni.
Opatrne sa uloží vedľa topánok.
Zvyčajne si vždy beriem so sebou čisté oblečenie.
Oblečenie sa tiež vloží do tašky.
Skontrolujem, či mám všetko.
Nakoniec sa taška položí pripravená k vchodovým dverám.
Tak sa na ňu zajtra ráno nezabudne.
Teraz sú všetky moje praktické úlohy na dnes vybavené.
Už sa len teším na pokojný večer.
