Zvyčajne v práci celý deň pozerám na obrazovku.
Preto by som teraz chcela byť úplne offline.
Idem do svojej obývačky.
Tu si rozsvietim svoju teplú lampu na čítanie.
Svetlo v miestnosti je teplé a mäkké.
Sadnem si do svojho mäkkého kresla.
Vyberiem si svoju novú knihu.
Je to skutočná papierová kniha.
Kniha sa otvorí a skutočný svet zmizne.
Kávové zrná od Niny sa musia odložiť na zajtra ráno.
Dnes večer pijem len pohár vody.
Telefón je po zvyšok večera ignorovaný.
Úplne relaxujem.
Takýto pokojný záver dňa je úplne dokonalý.
