Je štvrtok ráno a zvoní mi budík.
Zobudím sa a je mi naozaj hrozne.
Mám ťažkú hlavu a som veľmi unavená.
Otvorím oči, ale veľmi ma svrbia.
Vlastne to trochu bolí, keď žmurkám.
Skúšam sa napiť trochu vody z pohára na mojom stole.
Ale hrdlo mám úplne suché.
Keď prehĺtam, bolí ma v hrdle.
Pozriem sa na telefón, aby som zistila, koľko je hodín.
Je pol ôsmej a zvyčajne v tomto čase chodím autobusom.
Ale dnes nemám vôbec žiadnu energiu.
Necítim sa len unavená, ale naozaj chorá.
Určite by som dnes mala zostať doma a neísť do práce.
Píšem krátku správu svojmu kolegovi Petrovi.
Vysvetľujem, že som chorá a neprídem do kancelárie.
Rýchlo mi odpíše, že si mám jednoducho oddýchnuť a uzdraviť sa.
Mala by som zavolať do ambulancie, keď otvoria.
Ale práve teraz chcem len zavrieť oči a nechať ťažkú hlavu odpočívať.
