Nájdem telefónne číslo na svoju miestnu lekársku kliniku.
To číslo je tridsaťdva, štyridsaťpäť, šesťdesiatsedem, osemdesiatdeväť.
Zavolám im a čakám niekoľko minút.
Priateľská recepčná zdvihne telefón.
„Lekárska klinika, hovoríte s Hannou,“ hovorí.
Vysvetľujem, že som dnes naozaj ochorela.
„Mám ťažkú hlavu a svrbia ma oči,“ hovorím.
Tiež jej hovorím, že ma bolí hrdlo.
Pýta sa, či mám horúčku.
Odpovedám, že si to nemyslím, ale som veľmi unavená.
„Dnes by ste sa mali porozprávať s lekárom,“ hovorí recepčná.
Pozerá do kalendára, aby našla termín.
„Môžete prísť o jednej?“ pýta sa.
„Áno, to mi perfektne vyhovuje,“ odpovedám.
„Nezabudnite si so sebou vziať žltú zdravotnú kartu,“ hovorí.
Poďakujem jej a zložím.
Teraz si musím len trochu oddýchnuť, predtým ako tam pôjdem.
