Je niečo po jednej.
Pomaly kráčam k lekárskej klinike.
Je to krátka cesta, ale stále som veľmi ubolená a unavená.
Vyťahujem svoju žltú zdravotnú kartu.
Vonku svieti slnko.
Ale mala by som mať slnečné okuliare, pretože ma z toho svetla bolia oči.
Vchádzam do recepcie kliniky.
Na stene visí malý prístroj.
Tu si vždy treba naskenovať svoju žltú zdravotnú kartu.
Túto kartu som dostala poštou, keď som sa presťahovala do Dánska.
Skenujem žltú kartu na prístroji.
Vydá to tichý zvuk a zabliká nazeleno.
To znamená, že lekár vie, že som tu.
Vchádzam do samotnej čakárne.
Sadám si na voľnú stoličku a čakám.
