Sadnem si na stoličku v čakárni.
V miestnosti je takmer úplné ticho.
Trpezlivo čakám.
Moja hlava je stále veľmi ťažká.
Matka a malý chlapec sedia oproti mne.
Chlapec má možno päť rokov.
Drží si ruku na pravom uchu.
"Au, bolí ma ucho!" hovorí nahlas.
Jeho matka sa naňho pozerá.
"Ja viem, zlatko," hovorí jemne.
"Ale veľmi to bolí!" sťažuje sa chlapec.
"Lekár by nás mal čoskoro zavolať," hovorí matka.
Položí mu ruku okolo ramien.
Chlapec si nahlas povzdychne.
Vyzerá veľmi unavene.
Dobre mu rozumiem.
Moje vlastné hrdlo ma tiež veľmi bolí.
Chcem sa len znova cítiť dobre.
