Priateľský lekár otvorí dvere a zavolá moje meno.
Vojdem do jeho svetlej ordinácie.
Sadneme si k jeho stolu.
„Ako sa dnes cítite?“ pýta sa.
„Cítim sa naozaj zle,“ odpovedám.
Lekár sa na mňa pozrie.
„Kde vás to bolí?“ pýta sa milo.
Ukážem na svoje hrdlo.
„Veľmi ma bolí hrdlo,“ vysvetľujem.
„Je veľmi suché.“
Lekár prikývne a pozorne počúva.
„Moja hlava je tiež veľmi ťažká,“ pokračujem.
Dotknem sa svojej tváre.
„A moje oči sú úplne červené.“
Stále ma svrbia.
„Rozhodne by ste si mali oddýchnuť,“ hovorí.
Zapne malú baterku.
„Dovoľte mi pozrieť sa na vás bližšie,“ hovorí.
