Lekár ma žiada, aby som otvorila ústa.
„Povedzte á,“ hovorí s úsmevom.
Pozorne mi prezrie hrdlo.
Potom si vypočuje moje dýchanie.
Pýta sa, či sa cítim zle aj niekde inde.
Hovorím mu, že ma bolí aj hlava.
„Nie je to prechladnutie,“ hovorí.
„Máte bežnú jarnú alergiu,“ vysvetľuje.
Som trochu prekvapená.
Nikdy predtým som nemala alergiu.
Hovorí mi, že je to úplne normálne.
Tunajšie stromy a kvety sú pre moje telo nové.
„Mali by ste si v lekárni kúpiť nejaké mierne lieky,“ hovorí lekár.
Sľubuje, že to rýchlo pomôže.
„Potom sa budete cítiť opäť dobre,“ dodáva.
Veľmi sa mi uľavilo.
Bolí ma hrdlo, ale našťastie to nie je vážne.
