Cestou domov od lekára vojdem do miestnej lekárne.
Vytiahnem si z automatu číslo a chvíľu počkám.
Milá lekárnička vyvolá číslo tridsaťpäť.
Pristúpim k pultu a ukážem svoju žltú zdravotnú kartu.
Nájde môj recept v počítači.
Lekárnička mi dá malú škatuľku tabletiek na alergiu.
„Mali by ste užiť jednu tabletku každé ráno,“ hovorí.
Spýtam sa jej, či má niečo na hrdlo.
„Stále ma bolí hrdlo,“ vysvetľujem.
Prikývne a navrhne nejaké sladké pastilky na hrdlo.
„Pomáhajú, keď vás bolí hrdlo,“ hovorí.
„A dnes by ste tiež mali piť veľa vody.“
Poďakujem jej a kúpim si tabletky a pastilky.
Celkovo to stojí osemdesiatpäť korún.
Stále som unavená a ubolená, ale som rada, že mám lieky.
Teraz chcem ísť už len domov na svoju vlastnú pohovku.
