Je štvrtok večer a ja zvyčajne hrám bedminton.
Ale som stále chorá, takže to musím zrušiť.
Píšem správu svojmu spoluhráčovi v bedmintone.
Vysvetľujem, že som chorá a že ma bolí hlava.
Stále ma veľmi bolí aj hrdlo.
Dnes večer by som mala len oddychovať na gauči.
Prikrývam sa teplou dekou.
Beriem si svoj nový liek z lekárne.
Potom si pripravujem veľkú šálku horúceho čaju.
Do čaju si dávam veľkú lyžicu medu.
Môjmu boľavému hrdlu to robí naozaj dobre.
Horúci čaj pijem veľmi pomaly.
Čoskoro sa cítim trochu lepšie.
Zatváram oči a počúvam pokojnú hudbu.
Ešte sa necítim úplne dobre.
Ale našťastie sa už cítim trochu lepšie.
Mala by som ísť skoro do postele a spať.
