Je sobota ráno.
Zobúdzam sa skoro a opäť sa cítim naozaj dobre.
Celý piatok som doma oddychovala.
Mierny liek zaúčinkoval perfektne.
Moje oči sú jasné a vôbec ma nesvrbia.
Nemám bolesti hlavy a hrdlo ma už nebolí.
Vstávam z postele a otváram okno do mierneho jarného vzduchu.
Je krásne môcť dýchať bez problémov.
Idem do kuchyne pripraviť si poriadne raňajky.
Jem chlieb so syrom a pijem veľkú šálku horúcej kávy.
Slnko svieti, takže si myslím, že by som mala ísť na prechádzku do parku.
Obliekam si jarnú bundu a schádzam dole na ulicu.
Stromy sú teraz úplne zelené a veľa ľudí si užíva počasie.
Je naozaj otravné cítiť sa zle, keď je konečne jar.
Ale dnes cítim, že moje nohy sú silné, a mám späť svoju energiu.
Dám si pomalú prechádzku okolo malého jazera v parku.
Našťastie som už úplne zdravá a som pripravená užiť si víkend.
