Je ráno v Kodani.
Je január a je veľmi chladno.
Som trochu nervózna.
Dnes je veľký deň.
Je to pre mňa nový začiatok.
Je to môj prvý deň v novej práci.
Idem do práce autobusom.
Vystupujem na správnej zastávke.
Teraz idem posledný kúsok pešo.
Kde je kancelária?
Pozerám sa na veľké budovy.
Každá budova má číslo.
Tu je číslo tridsaťosem.
A tu je číslo štyridsať.
Idem o kúsok ďalej.
Tu je číslo štyridsaťdva.
A tam to je!
Tu je číslo štyridsaťštyri.
Vidím veľké logo.
Moja nová softvérová firma je priamo tu.
Mám dobrý pocit.
Som úplne pripravená.
