Teraz som v novej kancelárii.
Je to veľká a svetlá miestnosť.
Pri dverách stojí priateľský muž.
Usmieva sa na mňa.
„Vitaj!“ hovorí.
„Volám sa Peter.“
Podávam mu ruku.
„Ahoj Peter, volám sa Maya,“ hovorím.
Peter je kolega.
Kráčame spolu cez kanceláriu.
„Tu máš stôl,“ hovorí Peter.
Stôl má číslo šestnásť.
„A máš počítač,“ hovorí.
Dáva mi nový notebook.
Pozerám sa na svoje nové miesto.
Mám stoličku a veľký monitor.
„Veľmi pekne ďakujem, Peter,“ hovorím.
Som pripravená na svoj prvý pracovný deň.
