Mám obedňajšiu prestávku.
Som v predajni telefónov.
Mám telefón z Mexika.
Predavač je mladý muž.
„Máte dánsku SIM kartu?“ pýtam sa.
„Áno, samozrejme,“ odpovedá.
Dávam mu svoj telefón.
Vkladá SIM kartu do telefónu.
Telefón je teraz pripravený.
„Vaše nové číslo je dvanásť, tridsaťštyri, päťdesiatšesť, sedemdesiatosem,“ hovorí.
Mám v taške zápisník.
Zapisujem si to číslo.
„Dvanásť, tridsaťštyri, päťdesiatšesť, sedemdesiatosem,“ opakujem.
„Áno, presne tak,“ hovorí predavač.
„Ďakujem za pomoc,“ hovorím.
Teraz mám dánske číslo!
Dávam si telefón do vrecka.
