Je nasledujúce ráno.
Dnes som na veľkom registračnom úrade.
Je tu vnútri veľa ľudí.
Mám svoj pas a papiere v taške.
Všetko je pripravené na moju registráciu.
Stojím pri červenom automate.
Stlačím tlačidlo.
Automat mi vydá malý lístok s číslom.
Aké je moje číslo?
Pozriem sa na papier.
Mám číslo päťdesiatdeväť.
Je to dosť vysoké číslo.
Veľká obrazovka na stene ukazuje číslo.
Obrazovka ukazuje len číslo dvadsaťjeden.
Mám dosť času.
Nájdem si voľnú stoličku.
Sadnem si so svojimi papiermi.
Teraz čakám na svoj rad.
