Obrazovka ukazuje moje číslo.
To číslo je päťdesiatdeväť.
Idem k priehradke.
Za priehradkou sedí muž.
"Dobré ráno," hovorí.
"Dobré ráno," odpovedám.
"Volám sa Maya a mám tridsaťjeden rokov," hovorím.
"Vitajte, Maya," hovorí.
"Máte svoj pas?" pýta sa.
"Áno, mám svoj pas a svoje papiere," odpovedám.
"Nech sa páči," hovorím.
Pozerá sa na papiere.
Píše na svojom počítači.
Dostávam dánske osobné identifikačné číslo.
To číslo je súkromné a veľmi dôležité.
Dáva mi novú kartu.
"Nech sa páči, tu je vaša karta," hovorí.
"Teraz ste zaregistrovaná v Dánsku."
Usmievam sa a beriem si kartu.
Teraz som súčasťou Dánska.
