Znova som vonku na ulici.
Všetko je konečne na svojom mieste.
Je čas na malú oslavu.
Na rohu vidím malú pekáreň.
Idem dovnútra.
Krásne to tu vonia.
Za pultom stojí pekár.
„Dobrý deň,“ hovorí pekár.
„Dobrý deň,“ odpovedám.
Ukážem na koláč za sklom.
„Prosila by som si škoricové osie hniezdo,“ hovorím.
„Áno, samozrejme,“ hovorí.
„Koľko stojí?“ pýtam sa.
„Stojí dvadsaťpäť korún,“ odpovedá pekár.
Peňaženku mám v taške.
Vyberiem platobnú kartu.
Zaplatím za svoje škoricové osie hniezdo.
Pekár mi dá malé vrecúško.
Teraz mám škoricové osie hniezdo na svoju malú oslavu.
