Je ráno v Kodani.
Idem na autobusovú zastávku.
Počasie je dnes veľmi chladné.
Fúka.
Vietor je ľadový.
Mrznem.
Mám na sebe tenkú bundu.
Moja bunda vôbec nie je teplá.
Mám obuté aj tenké topánky.
Nemám na sebe teplý šál.
Moje ruky sú veľmi studené.
Trasiem sa.
Zima v Dánsku je tvrdá.
Potrebujem teplé oblečenie.
Potrebujem hrubý sveter.
Potrebujem aj veľký šál.
A potrebujem teplé rukavice.
Kráčam veľmi rýchlo.
Po práci si kúpim zimné oblečenie.
