Skončila som v práci.
Kráčam po pešej zóne.
Vietor je stále veľmi studený.
Vidím veľký obchod s oblečením.
Obchod je veľmi svetlý.
Idem do obchodu.
Je tu úžasne teplo.
Za pokladňou stojí predavačka.
Pozerá sa na mňa a usmieva sa.
"Dobrý deň," hovorí.
"Dobrý deň," odpovedám.
"Je mi veľmi zima," hovorím.
"Mám na sebe len tenkú bundu."
"Chcela by som nájsť nejaké teplé veci."
Predavačka sa opäť usmeje.
"Dnes je tiež veľmi chladno," hovorí.
"Máme veľa hrubých svetrov."
"Máme aj teplé zimné oblečenie."
"Len sa pokojne poobzerajte," hovorí milo.
"Veľmi pekne ďakujem," odpovedám.
