Pozerám sa na oblečenie na policiach.
Vidím hrubý sveter.
Je červený.
Potrebujem teplý sveter.
Obchod má veľa veľkostí.
Nachádzam veľkosť medium.
Vchádzam do skúšobnej kabínky.
Obliekam si červený sveter.
Mám ho na sebe a pozerám sa do veľkého zrkadla.
Sveter perfektne sedí.
Je neuveriteľne teplý.
Milujem tú červenú farbu.
Pozerám sa na cenovku.
Sveter stojí tristo korún.
Je to dobrá cena za hrubý sveter.
Znovu si sveter vyzliekam.
Kupujem si ho.
