Potrebujem aj zimnú bundu.
Pozerám si v obchode ďalšie oblečenie.
Nájdem krásny zelený kabát.
Je to veľmi krásny dizajn.
Oblečiem si ten zelený kabát.
Ale je príliš malý.
Cez ramená je veľmi tesný.
"Máte ho v inej veľkosti?" pýtam sa.
Predavačka sa pozrie.
"Nie, bohužiaľ," odpovedá.
Takže zelený kabát zavesím naspäť.
Predavačka mi nájde inú bundu.
Je to teplá, tmavomodrá zimná bunda.
Oblečiem si tú tmavomodrú bundu.
Sedí perfektne.
Je príjemne veľká a nie je tesná.
Pozriem sa do veľkého zrkadla.
Páči sa mi.
"Vezmem si ju," hovorím.
