Idem k stolu v obchode.
Na stole je veľa vecí.
Dnes nemám na sebe šál.
Je mi veľmi zima na krk.
Vidím modrý šál.
Je to veľmi dlhý šál.
Je vyrobený z vlny.
Vezmem ten modrý šál.
Dám si ho okolo krku.
Je úžasne teplý.
„To je pekná farba,“ hovorí predavačka.
„Áno, a je veľmi mäkký,“ hovorím.
Pozerám sa na cenovku.
Stojí stopäťdesiat korún.
To je dobrá cena za teplý šál.
Znova si ho dám dole.
„Kupujem si ho tiež,“ hovorím jej.
Položím modrý šál k červenému svetru.
