Stále mám na sebe svoju tenkú bundu.
Myslím na svoje studené ruky z dnešného rána.
Potrebujem hrubé rukavice.
Rozhliadam sa po svetlom obchode.
Vidím veľký kôš.
Kôš je plný rukavíc.
Nachádzam pár čiernych zimných rukavíc.
Sú veľmi hrubé a mäkké.
Nasadzujem si rukavice.
Perfektne mi sedia.
Pýtam sa usmievajúcej sa predavačky.
„Koľko stoja čierne rukavice?“ pýtam sa.
„Stoja stodvadsať korún,“ odpovedá.
Stodvadsať korún je dobrá cena.
Moje ruky sú už teplé.
„Vezmem si ich,“ hovorím radostne.
Znovu si dávam rukavice dole.
Dávam čierne rukavice spolu so svojím červeným svetrom a modrým šálom.
Teraz som pripravená platiť.
