„Tašku?“ pýta sa predavač.
„Nie, ďakujem,“ hovorím.
Nepotrebujem tašku.
Hneď si obliekam nové oblečenie.
Najprv si obliekam hrubý červený sveter.
Potom si obliekam tmavomodrú zimnú bundu.
Zapínam si teplú bundu.
Následne si beriem dlhý modrý šál.
Omotávam si ho okolo krku.
Nakoniec si dávam nové čierne rukavice.
Teraz mám na sebe všetko svoje teplé oblečenie.
Usmievam sa a hovorím dovidenia.
Vychádzam z obchodu.
Opäť stojím vonku na chladnej ulici.
Je mrazivá zima.
Vietor silno fúka.
Ale vôbec mi nie je zima.
Teraz som pripravená na zimu.
