Dnes ráno som sa skoro zobudila.
Slnko jasne svietilo do mojej spálne.
Ležala som v posteli a myslela na svoj domov v Mexiku.
Dnes mám totiž narodeniny.
Dnes mám tridsaťdva rokov.
Sú to moje prvé narodeniny ďaleko od rodiny.
Cítila som sa kvôli tomu trochu nostalgicky.
Ale potom som si z nočného stolíka vzala telefón.
Moja rodina mi poslala veľa láskyplných správ.
Napísali ich v noci, kým som spala.
Moji rodičia nahrali vtipné video s Lolou, naším psom.
Moja sestra Sofía napísala dlhú a milú správu.
A môj brat Diego poslal fotku mojej obľúbenej torty.
Keď som tú fotku uvidela, široko som sa usmiala.
Vôbec na môj veľký deň nezabudli.
Na všetky správy som okamžite odpovedala.
Napísala som im, že ich ľúbim a chýbajú mi.
Čítam si tie správy znova a znova.
Je to fantastický začiatok mojich narodenín.
