Sedím za svojím stolom v kancelárii.
Dnes som prišla skoro.
Pracujem tu už pol roka.
Zrazu k môjmu stolu prídu Peter a Eva.
Peter nesie malú tortu s jednou sviečkou.
"Všetko najlepšie k narodeninám, Maya!" povedia zborovo.
Som naozaj šťastná a veľmi prekvapená.
"Ďakujem veľmi pekne," poviem im.
Eva sa široko usmeje.
"Tú tortu sme kúpili dnes ráno v pekárni," vysvetľuje.
"Áno, a ja som nám urobil kávu," dodáva Peter.
Položí veľkú šálku kávy na môj stôl.
"Ste jednoducho takí zlatí," hovorím.
"Keď som pracovala v Mexiku, málokedy sme dostávali ráno tortu."
Peter a Eva prisunú k stolu dve stoličky.
Spolu jeme tortu a je to fantastický začiatok môjho dňa.
