Je sobotné dopoludnie a v kaviarni som skončila.
Práve som utrela posledný stôl.
Odväzujem si zásteru a kladiem ju na stoličku.
Dnes som mala krátku zmenu.
Minulý týždeň som pracovala do tretej.
V ten deň sme mali celý deň veľmi veľa práce.
Ale dnes sme mali len pár hostí.
Vonku svieti slnko a je krásny letný deň.
Dnes večer je dole pri mori veľká vatra.
Veľmi sa teším, až ju uvidím.
Beriem si telefón a píšem správu Eve.
Pýtam sa jej: „Stále platí, že sa dnes večer stretneme?“
Píšem aj to, že už mám voľno.
„Dnes som skončila skoro, takže som pripravená,“ píšem.
Eva odpovedá takmer okamžite.
„Áno, samozrejme!“ odpovedá.
„Práve som kúpila čerstvé jahody.“
„Uvidíme sa neskôr na pláži,“ píše.
Usmievam sa a beriem si tašku.
Potom vychádzam von do teplého letného počasia.
