Sama kráčam dole k pláži.
Je už večer, ale obloha je stále veľmi svetlá.
Slnko ešte nezačalo zapadať.
Pozriem sa hore a spomínam na január.
Vtedy som po práci často čakala na autobus.
Boli len štyri hodiny poobede.
Ale všade už bola úplná tma.
Stála som na autobusovej zastávke a mrzla.
Teraz tu žijem už pol roka.
Všetko sa zmenilo.
V Mexiku slnko vždy zapadalo takmer v rovnakom čase.
Takto to bolo po celý rok.
Tu som nikdy predtým nezažila také dlhé dni.
Svetlo dalo mestu úplne nový život.
Obliekam si svoj teplý sveter.
Hoci je obloha svetlá, od mora fúka trochu chladný vietor.
Teším sa, až uvidím vatru.
Bude to krásny večer s mojimi priateľmi.
