Je takmer dvanásť v noci, ale obloha je stále svetlá.
Má jemnú, modrú farbu.
Kráčam po ulici spolu s Evou a Petrom.
Veľa nerozprávame.
V noci znejú len naše kroky.
Pozerám sa na svojich priateľov.
Eva sa usmieva a Peter vyzerá unavený, ale šťastný.
Keď som sem prišla, nikoho som nepoznala.
Ale odvtedy sa veľa zmenilo.
Mám tu dobrý každodenný život a spoznala som veľa ľudí.
Vlastne som si našla skutočných priateľov.
Peter bol prvý kolega, s ktorým som sa rozprávala.
A Eva ma nedávno pozvala k sebe domov.
Teraz tu spolu kráčame pod svetlou letnou oblohou.
Práve som dovŕšila tridsaťdva rokov.
Vybudovala som si život, ktorý milujem.
Konečne sa v mojom novom meste cítim úplne ako doma.
