Každú stredu večer chodím do fitnescentra.
Rada cvičím.
Ale chcem sa venovať aj nejakému športu.
Milujem hrať bedminton.
Hrala som ho veľa doma v Mexiku.
Teraz hľadám nejaký miestny klub.
Sedím na gauči so svojím počítačom.
Hľadám na internete.
Nájdem dobrý bedmintonový klub.
Pozerám si webovú stránku klubu.
Majú veľa tímov.
Hrajú vo štvrtok večer.
Chcem si rezervovať skúšobný tréning.
Na webovej stránke nájdem formulár.
Napíšem svoje meno a svoj e-mail.
Vyberiem si štvrtok večer.
Tréning sa začína o siedmej večer.
Je to perfektné.
Teším sa, že si znova zahrám.
