Je štvrtok večer a som doma.
Balím si športovú tašku.
Dávam si topánky a oblečenie do tašky.
Teším sa, že si dnes večer zahrám.
Idem autobusom do veľkej športovej haly.
Je chladný zimný večer.
Sedím v autobuse a pozerám sa von.
Autobus zastavuje a ja vystupujem.
Vchádzam do veľkej športovej haly.
Je veľmi svetlá.
Vidím v hale veľa ľudí.
Milujú športovať.
Počujem hlasný zvuk.
Topánky pískajú na mnohých drevených kurtoch.
Ľudia rýchlo behajú a hrajú spolu.
Vyzerá to veľmi zábavne.
Som pripravená hrať.
Ale najprv si musím požičať raketu.
