Idem k bedmintonovému kurtu.
Na kurte stoja traja ľudia.
„Ahoj, volám sa Kasper,“ hovorí muž.
„A ja sa volám Sara,“ hovorí žena.
Tretí hráč sa volá Emil.
„Ja sa volám Maya,“ hovorím.
„Zvyčajne hráme štvorhru,“ hovorí Kasper.
„Chceš hrať s nami?“ pýta sa.
„Áno, veľmi rada,“ odpovedám.
Veľmi rada hrám bedminton.
Kasper a ja hráme proti Sare a Emilovi.
Ihneď začíname hrať.
Sara začína zápas.
Košík lieta rýchlo tam a späť.
Emil odbije košík vysoko do vzduchu.
Milujem smečovať.
Vyskočím a silno ho zasmečujem ponad sieť.
Dopadne na ich stranu kurtu.
„Dobrý úder, Maya!“ kričí Kasper.
