Rýchly zápas sa skončil.
Spoločne schádzame z kurtu.
Som veľmi unavená.
Kasper a Sara sú tiež unavení.
Pijeme trochu vody.
„Hráš veľmi dobre,“ hovorí Sara.
„Veľmi pekne ďakujem,“ hovorím.
„Myslím si, že je to veľká zábava.“
„Hrávaš často?“ pýta sa Kasper.
„Áno, doma v Mexiku hrám veľa,“ odpovedám.
„Zvyčajne hrám so svojou sestrou.“
„Je to zábavný šport,“ hovorí Sara.
„Veľmi radi hráme tu v klube.“
„Chcem hrať viac tu v Dánsku,“ hovorím.
„Rozhodne si rýchla,“ smeje sa Kasper.
„Vďaka, ale teraz si chcem sadnúť,“ hovorím.
„Pôjdeme do bufetu?“ pýta sa Kasper.
„Áno, veľmi rada,“ odpovedám.
