Vojdeme do malého bufetu v hale.
Nájdeme si stôl.
Som veľmi smädná.
Pijeme studenú vodu a rozprávame sa.
„Toto je naozaj dobrý klub,“ hovorím.
„Je to dobrý šport,“ hovorí Kasper.
Kasper sa na mňa pozrie.
„Chceš sa znova pridať?“ pýta sa.
„Áno, veľmi rada,“ odpovedám.
„Chcem tu hrať každý štvrtok,“ vysvetľujem.
„To znie skvelo,“ hovorí Sara.
„Vždy tu hráme vo štvrtok,“ hovorí Kasper.
„Tak sa uvidíme budúci týždeň,“ hovorím radostne.
Vypijeme zvyšok našej vody.
Je príjemné spoznávať nových ľudí.
