Sara a ja vychádzame zo športovej haly.
Je neskoro a je chladný zimný večer.
Ale po zápase mi je stále teplo.
Spolu kráčame k autobusovej zastávke.
Fúka vietor a ulica je tmavá.
„Tiež rada hráš bedminton cez víkend?“ pýtam sa.
„Nie, bedminton hrám len vo štvrtok,“ odpovedá Sara.
„Ale rada športujem,“ hovorí.
„Zvyčajne si chodím zabehať do parku,“ pokračuje.
Je to veľmi aktívna a zábavná osoba.
Čakáme na autobus v chlade.
„Môj autobus príde o desať minút,“ hovorím.
„Ideme rovnakým autobusom,“ usmieva sa Sara.
Veľmi sa z toho teším.
Rada sa s ňou rozprávam.
Kasper a Sara sú zábavní a milí ľudia.
Teraz mám vo štvrtok dobrú rutinu.
Som unavená, ale mám dobrú náladu.
Autobus konečne prichádza.
Už teraz sa teším na ďalší štvrtok.
