Môj budík zvoní nahlas.
Je ráno, ale stále je tma.
Otváram oči.
Pozerám sa smerom k oknu.
Vonku je úplná tma.
Slnko ešte vôbec nevyšlo.
V Dánsku je stále zima.
Ráno je tu neuveriteľne tma.
Rozvidnieva sa veľmi neskoro.
Pomaly si sadám v posteli.
Mimo periny je chladno.
Zapínam lampu na stole.
S trochou svetla je to hneď príjemnejšie.
Za oknom je obloha stále úplne čierna.
V Mexiku je teraz často veľa slnečného svetla.
Ale tu slnko spí.
Je ťažké zobudiť sa v tme.
Pozerám sa na hodiny.
Vstávam z postele.
Deň sa teraz začína.
