Stojím pri okne v obývačke.
Pozerám sa von na mesto.
Obloha už nie je čierna.
Pomaly sa mení na sivú.
Slnko vychádza neskoro.
Beriem si telefón.
Čítam si predpoveď počasia na dnes.
Práve teraz je veľmi chladno.
Sú len dva stupne.
Ale vonku je stále sucho.
Neskôr bude veľmi mokro.
Čoskoro bude pršať.
Bude aj veterno.
Neskôr cez deň bude silno fúkať.
Bude to pravý zimný deň.
Položím telefón na stôl.
Ešte raz sa pozriem na oblohu.
