Dnes je chladno.
Je zima a ráno je tma.
Stojím vo svojej izbe a chystám sa.
Nájdem svoje teplé zimné oblečenie.
Najprv si oblečiem hrubý sveter.
Pretiahnem si ho cez hlavu.
Sveter je príjemne teplý a mäkký.
Vezmem si aj dlhý šál.
Pevne si ho omotám okolo krku.
Potom vyjdem do predsiene.
Zo schodiska ide studený prievan.
Vezmem si svoju ťažkú zimnú bundu.
Zapnem si bundu na zips až celkom hore.
To zastaví studený vzduch.
Dnes je dôležité zostať v teple.
Tak v chlade nebudem mrznúť.
Zoberiem si so sebou aj svoj dáždnik.
Konečne som pripravená ísť na svoj autobus.
Otvorím vchodové dvere a vyjdem do chladu.
