Vystupujem z autobusu neďaleko práce.
Pevne si držím šál.
Počasie je dnes veľmi divoké.
Kráčam po ulici.
Zrazu je veľmi veterne.
Silný vietor fúka proti mne.
V ruke mám otvorený dáždnik.
Ale vietor je príliš silný.
Rýchlo sa to stáva problémom.
Dáždnik lieta zo strany na stranu.
Teraz je to nemožné.
Zápasím s ním.
Nakoniec dáždnik zatváram.
Bez neho je veľmi zima.
Dážď mi udiera do tváre.
Ponáhľam sa cez vietor.
Vchod do kancelárie je priamo vpredu.
Vstupujem do budovy.
Našťastie je tu vnútri teplo a ticho.
