Sedím za svojím stolom v kancelárii.
Píšem kód na svojom počítači.
Pozerám sa z okna.
Dnes je veľmi zlé počasie.
Obloha je tmavá a ťažká.
Vonku je úplne sivo.
Neustále prší na sklo.
Tiež veľmi fúka.
Pozerám sa na hodiny na stene.
Je len skoré popoludnie.
Ale veľmi rýchlo sa robí pochmúrne.
Svetlo mizne v sivej oblohe.
V tomto ročnom období sa skoro stmieva.
Je to typické zimné popoludnie v Dánsku.
Tam vonku vo vetre je veľmi chladno.
Ale tu vnútri je príjemne teplo.
Pijem trochu horúcej kávy zo svojej šálky.
Minútu počúvam dážď.
Potom sa opäť pozriem na obrazovku svojho počítača.
Pokračujem so svojím kódom.
