Skončila som na dnes s prácou.
Balím si tašku.
Lúčim sa s Petrom v kancelárii.
Vychádzam z kancelárskej budovy.
Zastavujem sa na ulici a pozerám na oblohu.
Už som na to zvyknutá.
Je ešte len popoludnie.
Ale už je úplná tma.
Všade svietia pouličné lampy.
Mesto vyzerá v tme úplne inak.
Je to veľmi iné ako v Mexiku.
Vietor stále silno fúka.
Teraz sa rýchlo ochladzuje.
Vyťahujem si svoj hrubý šál.
Kráčam po ulici v slabom svetle.
Idem smerom k autobusovej zastávke.
Čakám na autobus v tme.
