Odomykám dvere.
Konečne som doma vo svojom byte.
Vonku je mokro a veterno.
Ale tu vnútri je teplo.
Moja zimná bunda je veľmi mokrá.
Vyzliekam si bundu.
Z môjho dáždnika tiež kvapká voda.
Idem do kúpeľne.
Položím dáždnik na podlahu.
Voda kvapká dole na dlaždice.
Potom idem do obývačky.
Je tu úplná tma.
Skoro nič nevidím.
V rohu je malá lampa.
Zapnem lampu.
Svetlo je žlté a mäkké.
V obývačke je hneď svetlejšie.
Teraz je obývačka teplá a svetlá.
Je príjemné byť teraz vnútri.
