Počula som, že mnohí Dáni vo svojom voľnom čase pracujú ako dobrovoľníci.
Páči sa mi ten nápad.
Chcem sa naučiť lepšie hovoriť po dánsky a spoznať nových ľudí.
Jeden večer sedím pri svojom počítači.
Nájdem si webovú stránku pre dobrovoľnícku prácu.
Prečítam si prvé tri inzeráty na stránke.
Prvý inzerát je zo športového klubu.
Ale potrebujú pomoc vo štvrtok večer a vtedy hrám bedminton.
Druhý inzerát je z múzea.
Potrebujú človeka v stredu večer, ale vtedy cvičím.
Potom sa pozriem na tretí inzerát.
Je z tej malej kaviarne, ktorú už poznám.
Potrebujú ľudí na sobotu dopoludnia.
To mi úplne perfektne vyhovuje.
Vyplním krátky formulár so svojím menom a e-mailovou adresou.
Napíšem aj svoje telefónne číslo: dvanásť, tridsaťštyri, päťdesiatšesť, sedemdesiatosem.
Nakoniec stlačím odoslať.
Ešte nikdy predtým som v kaviarni nepracovala, ale som pripravená sa to naučiť.
