Je to moja prvá sobotná zmena v malej kaviarni.
Prišla som skoro.
Slnko svieti na ulici v Kodani.
Teším sa, ale som aj trochu nervózna.
Je to prvýkrát, čo pracujem v kaviarni.
Išla som do zadnej miestnosti, aby som sa pripravila.
Na stole pre mňa ležala nová zástera.
Obliekla som si ju a zaviazala na chrbte.
Bol to dobrý pocit, mať ju na sebe.
Teraz som pripravená začať.
Musím sa naučiť správne otvárať kaviareň.
Najprv vedúci odomkol ťažké vchodové dvere.
Potom som vyšla na chodník, aby som všetko pripravila.
Vyniesla som von štyri stoličky.
Rozostavila som ich okolo malého stola.
O chvíľu prídu ostatní dobrovoľníci.
Som veľmi nadšená zo svojho prvého dňa.
