Je to môj prvý raz za pultom.
Kaviareň ešte nie je otvorená.
Jeden zo skúsených dobrovoľníkov ma volá.
Stojíme pred veľkým kávovarom na espresso.
„Dnes sa musíš naučiť pripravovať kávu,“ hovorí.
Nikdy predtým som na takomto prístroji kávu nepripravovala.
Prvým krokom je pomlieť kávové zrná.
Stlačí malé tlačidlo.
Prístroj s hlasným zvukom melie hnedé zrná.
Druhým krokom je napeniť mlieko.
Nalieva studené mlieko do kovovej kanvičky.
Potom zapne horúcu paru.
Medzitým pozorne sledujem jeho ruky.
Mlieko v kanvičke sa rýchlo zohrieva a hustne.
Očividne už predtým veľakrát pripravoval kávu.
Keď som dnes ráno prišla, bola som veľmi nervózna.
Ale vysvetlil to dobre, takže som už väčšinu z toho pochopila.
