Dnes dopoludnia sme mali neuveriteľne veľa práce.
Práve som pripravila svoje úplne prvé cappuccino.
Chvíľu pred desiatou prišiel k pultu nejaký muž.
„Jedno cappuccino, prosím,“ povedal.
Práve som sa naučila používať kávovar na espresso.
Takže som hneď podišla k prístroju.
Uvarila som kávu a ponorila parnú trysku do mlieka.
Ale držala som ju trochu príliš hlboko.
Asi som bola trochu príliš nervózna.
Bohužiaľ, na mlieku sa nevytvorila žiadna hustá pena.
Opatrne som sa pozrela dole do kanvičky.
Pena nebola úplne dokonalá.
Ale aj tak vyzerala prijateľne.
Naliala som horúce mlieko na kávu v šálke.
Potom som kávu podala mužovi so zdvorilým úsmevom.
„Nech sa páči, bude to päťdesiatpäť korún,“ povedala som.
Vzal si šálku a sadol si k prvému stolu.
