Krátko nato prišla ďalšia objednávka.
Dnes som už pripravila svoju prvú kávu.
Ale tento zákazník chcel iba jedlo.
Objednal si žemľu so syrom.
Z košíka som vzala teplú kváskovú žemľu.
Kváskový chlieb má často tvrdú kôrku.
Ale naučila som sa chlieb rýchlo prekrojiť na polovicu.
Potom som na žemľu položila hrubý plátok syra.
Jedlo som pekne naservírovala na malý tanier.
Teraz som ho musela zaniesť zákazníkovi.
Uprostred kaviarne stálo veľa ľudí.
Balansovala som s tanierom a opatrne som kráčala dopredu.
Pomaly som prešla okolo ostatných hostí.
Zákazník našťastie sedel úplne vzadu v rohu.
Čakal pri štvrtom stole.
Položila som tanier na stôl pred neho.
"Nech sa páči, teplá žemľa so syrom," povedala som.
"Veľmi pekne ďakujem," odpovedal muž.
Je pekné vidieť spokojného hosťa.
