Bola to moja druhá sobotná zmena v kaviarni.
Už som sa naučila robiť veľkú časť práce.
V to dopoludnie bolo vonku nádherne teplo.
K pultu pristúpila žena.
"Poprosila by som si zázvorové pivo," povedala.
"Samozrejme, moment," odpovedala som.
Podišla som k veľkej presklenej chladničke za pultom.
Pozrela som sa na tretiu policu.
Stáli tam studené fľaše zázvorového piva.
Našla som jednu fľašu a vybrala ju.
Zázvor ležal dole na dne ako hustý oblak.
Naučila som sa to premiešať predtým, než fľašu otvorím.
Tak som fľašu veľmi opatrne otočila hore dnom.
Držala som ju takto pár sekúnd.
Zázvor sa pomaly zmiešal so zvyškom tekutiny.
Teraz nápoj vyzeral presne tak, ako mal.
Znova som fľašu otočila a položila ju na pult.
"Nech sa páči, bude to tridsaťpäť korún," povedala som jej.
Zaplatila a svoj studený nápoj si pravdepodobne vychutnala.
