Neskôr v tú istú sobotu sme mali opäť veľmi veľa práce.
Mladá žena prišla k pultu a objednala si veľké cappuccino.
Moja prvá šálka nebola úplne dokonalá.
Ale tentoraz som bola pripravená.
Vzala som kovovú kanvičku a naliala do nej studené mlieko.
Položila som kanvičku pod kávovar a zapla horúcu paru.
Nezvýšila som tlak hneď.
Naučila som sa totiž počúvať kávovar.
Hlasný zvuk pary bol tentoraz úplne správny.
Mlieko sa pomaly zohrievalo.
A pena navrchu sa stala veľmi hustou a jemnou.
Bol to veľký krok vpred.
Opatrne som naliala mlieko na kávu vo veľkej šálke.
Naozaj to vyzeralo ako skutočné profesionálne cappuccino.
„Nech sa páči,“ povedala som a položila šálku na pult.
Žena sa usmiala a vzala si kávu.
Konečne som sa naučila ovládať tlak.
