V moju tretiu sobotu som stála pripravená za pultom.
Konečne som sa naučila v kaviarni trochu uvoľniť.
Cez okno som videla na ulici staršieho muža.
Pomaly kráčal k vchodovým dverám.
Bol tu aj na mojej prvej a druhej zmene.
Je jedným zo stálych zákazníkov kaviarne.
Naučila som sa jeho objednávku naspamäť.
Vždy si kupuje presne to isté.
Otvoril dvere a prišiel k pokladni.
Pozrela som sa na neho a usmiala sa.
„Dobré ráno,“ povedala som.
„Mám vám pripraviť vaše zvyčajné cortado?“
Muž sa na mňa prekvapene pozrel.
Potom sa radostne usmial.
„Áno, prosím, budem veľmi rád,“ odpovedal.
Podišla som ku kávovaru na espresso.
Kávu som pripravovala už mnohokrát, takže to išlo rýchlo.
Bol to dobrý pocit, poznať našich hostí.
