Moja tretia smena v kaviarni sa konečne skončila.
Bola to veľmi rušná sobota.
Dočista som umyla veľký drevený pult.
Potom som išla do miestnosti pre personál.
Dala som si dole zásteru.
Zavesila som ju na prvý háčik na stene.
Na svojich prvých smenách som sa toho naučila naozaj veľa.
Konečne som sa naučila správne speniť mlieko.
Tiež som sa naučila zapamätať si objednávku stáleho zákazníka.
Bola to zábava, ale bola som aj trochu unavená.
Vzala som si tašku zo stola.
Potom som išla k hlavným dverám.
Teraz to prevzala poobedná smena.
Vykročila som na ulicu.
Poobedné slnko jasne svietilo nad mestom.
Cestou k autobusu som sa sama pre seba usmiala.
Mám veľkú radosť zo svojej novej dobrovoľníckej práce.
Už teraz sa teším na svoju štvrtú smenu.
