Je pondelok ráno.
Robím si šálku horúceho čaju.
Sedím za stolom v kuchyni.
Otváram svoj kalendár.
Vždy si tu plánujem svoj týždeň.
Teraz je február.
Mesiac je už veľmi plný.
Zajtra je utorok.
Môj bicykel je bohužiaľ pokazený.
Zajtra ráno idem pešo k opravárovi bicyklov.
Otvára o ôsmej.
Zapisujem si to do kalendára.
Dnes volám aj kaderníkovi.
Moje vlasy sú až príliš dlhé.
V stredu idem do posilňovne.
V stredy často trénujem.
Zvyčajne je to o siedmej večer.
Znova sa pozerám na svoj plán.
Pijem svoj čaj.
Teraz som pripravená na nový týždeň.
