Je utorok ráno.
Je štvrť na deväť.
Tlačím svoj bicykel.
Je pokazený.
Vchádzam k opravárovi bicyklov.
Často pracuje skoro.
Dielňa je plná bicyklov.
Opravár bicyklov vzhliadne.
„Dobré ráno,“ hovorí.
„Dobré ráno,“ hovorím.
„Môj bicykel je pokazený.“
Berie si môj bicykel.
„Dnes ho opravím,“ hovorí.
„Veľmi pekne ďakujem,“ hovorím.
Vychádzam z dielne.
Teraz kráčam na autobusovú zastávku.
Zvyčajne chodím do práce autobusom.
Väčšinou bicyklujem cez víkend.
Čoskoro príde môj autobus.
Je krásne ráno vo februári.
V práci som o trištvrte na deväť.
