Mám obednú prestávku.
Sedím v jedálni v práci.
Včera som mala veľa práce.
Preto teraz volám kaderníčke.
Beriem si svoj mobilný telefón.
Volám do kaderníckeho salónu v meste.
Telefón zdvihne žena.
„Dobrý deň, tu je kadernícky salón,“ hovorí žena.
„Dobrý deň, volám sa Maya,“ hovorím.
„Chcela by som si rezervovať termín na štvrtok.“
„Okamih,“ hovorí kaderníčka.
„Máte voľný termín popoludní?“ pýtam sa.
„Áno, máme voľný termín o pol piatej,“ hovorí.
„To mi veľmi vyhovuje,“ hovorím.
„Aké je vaše telefónne číslo?“ pýta sa kaderníčka.
„Moje číslo je dvanásť, tridsaťštyri, päťdesiatšesť, sedemdesiatosem,“ hovorím.
„Veľmi pekne ďakujem, uvidíme sa vo štvrtok o pol piatej,“ hovorí.
„Uvidíme sa,“ odpovedám.
Položím telefón na stôl.
Teraz konečne jem svoje jedlo.
