Beriem si telefón.
Otváram si kalendár.
Pozerám sa na štvrtok.
Zrazu vidím problém.
Mám termín u kaderníčky o pol piatej.
Moja káva s Ninou je tiež o pol piatej!
Ihneď posielam Nine esemesku.
Píšem: „Ahoj, Nina, prepáč.“
„Mám termín u kaderníčky vo štvrtok o pol piatej.“
„Máš namiesto toho čas o šiestej?“
Nina odpovedá veľmi rýchlo.
Píše: „Žiadny problém!“
„Vidíme sa o šiestej.“
Usmievam sa a mením čas v kalendári.
Teraz môj štvrtok dokonale sedí.
