Je štvrtok popoludní.
Mám po práci.
Kráčam k opravárovi bicyklov.
Je trištvrte na štyri.
Mechanik stojí v obchode.
„Ahoj,“ hovorím.
Vytlačí bicykel von ku mne.
„Váš bicykel je pripravený,“ hovorí.
„Veľmi pekne ďakujem,“ hovorím.
Bicykel vyzerá naozaj pekne.
Pneumatiky sú teraz tvrdé.
Vytlačím bicykel von na ulicu.
Dnes svieti slnko.
Nasadnem na bicykel.
Často bicyklujem v Kodani.
Je to veľmi jednoduché.
Teraz veselo bicyklujem ku kaderníkovi.
Termín mám o pol piatej.
Teším sa na to.
