Prichádzam ku kaderníčke o pol piatej.
Som vždy presná.
Kaderníčka ma pozdraví.
Umýva a strihá mi vlasy.
Trvá to asi hodinu.
Môj nový účes je veľmi pekný.
Ďakujem kaderníčke a odchádzam zo salónu.
Môj bicykel stojí vonku pred vchodom.
Bicyklujem cez mesto.
Je štvrtok večer.
Bicyklujem do útulnej kaviarne.
Zaparkujem bicykel a vojdem dnu.
Nina už sedí pri stole.
Pozriem sa na hodinky.
Je presne šesť hodín.
„Ahoj Maya, tvoje vlasy sú naozaj pekné,“ hovorí Nina.
„Veľmi pekne ďakujem,“ hovorím.
Objednáme si dve šálky kávy.
Pijeme kávu a rozprávame sa.
Vždy si užívam naše stretnutia pri káve.
