Je štvrtok večer a som v športovej hale.
Hrám tu bedminton každý týždeň.
Hrám zápas proti svojej kamarátke Sare z klubu.
Zápas je veľmi napínavý a vyrovnaný.
Hráme o úplne posledný bod.
Silno udrie do košíka.
Letí rýchlo ponad sieť smerom ku mne.
Urobím veľký krok cez kurt, aby som naň dosiahla.
Švihnem raketou celou svojou silou.
Perfektne trafím košík.
Dopadne presne na bielu čiaru.
Bod je môj a vyhrávam zápas.
Sara sa usmeje cez sieť a hovorí: „Dobrý zápas!“
„Veľmi pekne ďakujem, to bol ťažký bod,“ odpovedám.
Chvíľu stojím pri sieti, aby som popadla dych.
Veľmi sa potím a potrebujem prestávku.
V taške nájdem svoju červenú fľašu na vodu.
Vypijem veľa studenej vody.
Je skvelé rozhýbať telo po dlhom dni v kancelárii.
