V piatok popoludní idem na pokojnú prechádzku na slnku.
Nesiem svoju ťažkú zimnú bundu.
Už ju vôbec nepotrebujem.
Zastavím sa pred miestnou čistiarňou.
Otvorím dvere a vojdem dnu.
V malom obchode to vonia čistým oblečením a mydlom.
Za pultom stojí starší muž.
„Dobrý deň, chcela by som si dať vyčistiť túto bundu,“ hovorím.
Podávam veľkú bundu cez pult.
„Samozrejme,“ odpovedá muž a skúma látku.
„Bude hotová v stredu,“ hovorí.
„Bude to dvestopäťdesiat korún.“
Vyberám z tašky svoju platobnú kartu.
Zaplatím pri pokladni a dostanem malú žltú účtenku.
„Ďakujem veľmi pekne, prajem pekný víkend,“ hovorím.
„Aj vám,“ odpovedá s úsmevom.
Vložím si účtenku do tašky.
Potom znova vyjdem na rušný chodník.
Vychutnávam si prechádzku v teplom popoludňajšom slnku.
