Neskôr popoludní idem do miestneho supermarketu.
Musím nakúpiť na dnešný večer.
Nájdem nejaké čerstvé červené paradajky a vrecko fazule.
Potrebujem aj nejaké ostré koreniny.
Zaplatím pri pokladni a idem späť domov.
Moja kuchyňa je malá, ale je veľmi útulná.
Položím tašky na stôl a umyjem si ruky.
Idem uvariť veľkú porciu tradičného mexického guláša.
Je to jeden zo starých receptov mojej mamy.
Vyberiem drevenú dosku a ostrý nôž.
Strávim v kuchyni pohodovú hodinu.
Je príjemné stáť a krájať zeleninu.
Nakrájam paradajky a cibuľu na malé kúsky.
Tieto vône mi pripomínajú môj domov v Mexiku.
Ale teraz je to môj domov aj tu v Kodani.
Všetko to dám do veľkého hrnca na sporáku.
Guláš sa musí pomaly dusiť.
Zamiešam to a lyžicou ochutnám omáčku.
Chutí to úplne perfektne.
Veľmi sa teším na večeru s Ninou.
