V nedeľu popoludní sedím na pohovke vo svojej obývačke.
Slnko svieti cez okno a izba je krásne svetlá.
Na stole pred sebou mám počítač na dlhý videohovor.
Celá moja rodina v Mexiku je na obrazovke.
Vidím svojich rodičov, sestru Sofíu a brata Diega.
Náš pes Lola zrazu veľmi nahlas zašteká.
Nadšene poskakuje pred kamerou.
„Lole chýbaš,“ hovorí Sofía a smeje sa.
„Aj vy všetci mi chýbate,“ hovorím a kývam im.
Môj otec sa pýta na moju prácu a na môj každodenný život tu.
Rozprávam im o svojej práci, o bedmintone a o svojej milej susedke.
Rozprávame sa spolu viac ako hodinu.
Rozhliadam sa po svojej svetlej obývačke.
Dívam sa na tú peknú zelenú rastlinu zo včera.
Od januára ubehlo veľa času.
„Si rada, že tam bývaš?“ pýta sa moja mama.
Široko sa na ňu usmievam.
„Áno,“ odpovedám.
„Teraz sa v meste naozaj cítim ako doma.“
