Stojím pred supermarketom.
Supermarket je veľký a svetlý.
Dvere sa otvárajú automaticky.
Idem do obchodu.
Obchod má veľa tovaru.
Pri vchode sú kopy košíkov.
Beriem si košík.
Košík je červený a ľahký.
Hľadám zeleninu.
Oddelenie je hneď tu.
Vidím debničku na zemi.
Debnička je zelená.
V debničke je veľa mrkiev.
Mám rada mrkvu.
Vyberám si veľký zväzok.
Zväzok vyzerá veľmi čerstvý.
Vkladám zväzok do košíka.
Teraz košík nie je prázdny.
Idem ďalej do obchodu.
