Vidím zvláštnu zeleninu.
Tá zelenina je dlhý koreň.
Ten koreň je veľmi bledý.
Vyzerá ako biela mrkva.
Pozriem sa dole na ceduľku.
Na ceduľke je napísané „paštrnák“.
Nepoznám túto zeleninu.
Je to dánska zelenina?
Mám rada zeleninu.
Mám rada mrkvu.
Možno paštrnák chutí dobre.
Vezmem paštrnák do ruky.
Ten koreň je celkom veľký.
Chcela by som ho.
Pozriem sa na košík.
Vložím koreň do košíka.
Rada by som vyskúšala niečo nové.
