Idem k pultu v pekárni.
Tá vôňa je veľmi dobrá.
Mám rada koláče.
A naozaj mám rada škoricové hniezda.
Za pultom stojí pekár.
Pekár sa na mňa pozerá.
Usmieva sa.
„Čo si prosíte?“ pýta sa pekár.
Ukážem na škoricové hniezdo.
Ten koláč vyzerá lahodne.
„Dala by som si jedno škoricové hniezdo, prosím,“ hovorím.
„Áno, samozrejme,“ hovorí pekár.
Vezme koláč.
Vloží koláč do vrecka.
Podá vrecko cez pult.
„Nech sa páči,“ hovorí.
Vezmem si vrecko.
„Veľmi pekne ďakujem,“ hovorím.
Vložím vrecko do košíka.
