Teraz potrebujem mlieko.
Kráčam dlhou uličkou.
Pozerám sa na regál.
Vidím vodu a džús.
Ale neviem nájsť mlieko.
Pozerám sa všade.
Vidím muža.
Pracuje v supermarkete.
Zastavím zamestnanca a usmejem sa.
„Prepáčte,“ hovorím.
„Chcela by som mlieko.“
„Kde je mlieko?“
Muž ukáže do zadnej časti obchodu.
„Oddelenie mliečnych výrobkov je tam dole,“ hovorí.
„Veľmi pekne ďakujem,“ odpovedám.
Idem tam dole.
Konečne nachádzam chladničku a mlieko.
Vezmem si kartón a položím ho do košíka.
