Idem ďalej k inému regálu.
Pozerám sa na jedlo.
Supermarket má veľa vecí z iných krajín.
Hľadám chuť Mexika.
Chýba mi jedlo z domova.
Mám veľmi rada fazuľu.
Často jem čiernu fazuľu.
Pozerám sa na nízku policu.
Polica je trochu tmavá.
Ale vidím farebnú konzervu.
Konzerva stojí úplne vzadu.
Je to konzerva s čiernou fazuľou.
Usmievam sa.
Načiahnem ruku úplne dozadu.
Vytiahnem konzervu.
Čítam si etiketu na konzerve.
Je perfektná na moju večeru.
Dám konzervu do košíka.
Mám dosť jedla.
