Idem k pokladni.
V ruke mám košík.
Kladiem jedlo na pás.
Najprv vyberiem z košíka ražný chlieb.
Potom vezmem mlieko a paštrnák.
Vezmem aj mrkvu a čiernu fazuľu.
Nakoniec položím na pás koláč.
Pokladník sedí za pokladňou.
Usmieva sa na mňa.
„Dobrý deň,“ hovorí.
„Dobrý deň,“ odpovedám.
Rýchlo skenuje jedlo.
Vytiahnem svoju kartu.
Podržím kartu nad prístrojom.
Prístroj pípne.
„Chceli by ste bloček?“ pýta sa.
„Áno, prosím, chcela by som bloček,“ hovorím.
Otvorím si tašku.
Rýchlo si zbalím tašku.
„Pekný deň,“ hovorí.
