Som opäť doma v byte.
Stojím v kuchyni.
Vyprázdňujem tašku na kuchynskú linku.
Vybaľujem jedlo.
Beriem mlieko.
Dávam mlieko do chladničky.
Potom sa pozerám na paštrnák.
Je to smiešny koreň.
Použijem ho do mojej polievky.
Dávam paštrnák do chladničky.
Teraz chladnička nie je prázdna.
Beriem chlieb.
Ražný chlieb je veľmi ťažký.
Dávam chlieb do skrinky.
Potom beriem konzervu s fazuľou.
Fazuľa vydrží dlho.
Dávam konzervu do skrinky.
Teraz je v skrinke jedlo.
Som celkom hladná.
Rada by som si teraz dala večeru.
