V Kodani je zima.
Kráčam po ulici.
Vietor je veľmi studený.
Dnes silno fúka.
Opieram sa do studeného vetra.
Vyťahujem si šál vyššie.
Mrzne mi tvár.
Rozhliadam sa.
Chcela by som ísť do tepla.
Vidím malú kaviareň na rohu.
Okná sú zahmlené.
Vyzerá, že vo vnútri je teplo.
Kráčam ku kaviarni.
Otváram ťažké dvere.
Vchádzam dnu.
Vonia to tu kávou.
Vzduch je príjemne teplý.
Zatváram za sebou dvere.
Studený vietor zostáva vonku.
