Teraz som vnútri v kaviarni.
Je tu veľmi teplo.
Vyzliekam si hrubú zimnú bundu.
Je ťažká.
Nájdem háčik na stene.
Zavesím si bundu na háčik.
Dávam si dole aj šál a rukavice.
Kaviareň je malá a útulná.
Hľadám si dobré miesto.
Pri okne je malý stôl.
Stôl stojí vedľa radiátora.
Idem k stolu.
Sadnem si na stoličku.
Moje ruky sú stále studené.
Šúcham si ich o seba.
Moje ruky sa zohrievajú.
Je to fantastický pocit.
Teraz mi je už skoro teplo.
Som hladná a smädná.
Rada by som si teraz niečo objednala.
