Idem k presklenej vitríne.
Je plná koláčov a chleba.
Pozerám sa na to množstvo vecí.
Vyzerajú veľmi chutne.
Vedľa koláčov sú malé štítky.
Štítky sú ručne písané.
Čítam názvy na štítkoch.
Je tu veľa druhov pečiva.
Je ťažké si vybrať.
Je tam veľký čokoládový koláč.
Ale pozerám sa na iný kúsok pečiva.
Je to veľké škoricové hniezdo.
Na vrchu má veľa cukru.
Milujem chuť škorice.
Je to perfektné na chladný zimný deň.
Veľmi by som chcela to škoricové hniezdo.
Teraz som pripravená si objednať.
