Idem k pokladni.
Za pultom stojí mladý muž.
Je barista v kaviarni.
Usmejem sa naňho.
Prívetivo prikývne.
„Dobrý deň,“ hovorí.
„Čo si dáte?“ pýta sa.
„Dobrý deň,“ odpovedám.
„Dala by som si čiernu kávu, prosím.“
„A môžem poprosiť aj o škoricového slimáka?“
„Samozrejme,“ hovorí.
„Jedna čierna káva a škoricový slimák.“
„Chcete si sadnúť sem?“ pýta sa.
„Áno, prosím, sadnem si tamto,“ hovorím.
„V poriadku,“ hovorí barista.
„Teraz vám pripravím kávu.“
„Veľmi pekne ďakujem,“ hovorím.
