Čakám pri pulte.
Pripravuje moju kávu.
Položí horúcu šálku kávy na drevenú tácku.
Na tácku položí aj malý tanierik.
Môj škoricový slimák leží na tanieriku.
Vonia nádherne.
„Nech sa páči, vaša objednávka,“ hovorí.
„Veľmi pekne ďakujem,“ odpovedám.
„Ďakujem za dobrú obsluhu.“
„Rado sa stalo,“ hovorí milo.
Beriem tácku oboma rukami.
Kráčam veľmi opatrne po podlahe.
Kráčam späť k svojmu stolu pri okne.
Položím tácku na stôl.
Teraz by som si chcela sadnúť.
Som pripravená na dobrú prestávku.
