Jem posledný kúsok svojho škoricového slimáka.
Chutí naozaj dobre.
Ale je aj veľmi sladký.
Moja šálka na kávu je úplne prázdna.
Zrazu som veľmi smädná.
Chcela by som trochu studenej vody.
Okolo môjho stola prechádza mladý muž.
Pracuje tu v kaviarni.
Zbiera prázdne šálky a taniere.
Zachytím jeho pohľad.
Zastaví sa pri mojom stole a usmeje sa.
„Prepáčte,“ poviem zdvorilo.
„Áno?“ odpovie mladý muž.
„Môžem poprosiť o pohár vody z vodovodu?“ spýtam sa.
„Áno, samozrejme,“ povie.
„Ďakujem veľmi pekne,“ poviem.
Vezme môj prázdny tanier a šálku.
Kráča späť k pultu.
O chvíľu neskôr príde s pohárom studenej vody.
