Pijem svoju vodu.
Voda je studená a príjemná.
Beriem si tašku z podlahy.
Skončila som s prestávkou.
Idem k pultu.
Priateľský barista tam stále stojí.
Pozerá sa na mňa s úsmevom.
„Dali by ste si ešte niečo?“ pýta sa.
„Nie, ďakujem,“ odpovedám.
„Chcela by som platiť.“
„Áno, samozrejme,“ hovorí.
Pozerá sa na svoju malú obrazovku.
„Jedna čierna káva a jedna škoricová rolka,“ hovorí.
„Áno, to súhlasí,“ hovorím.
„Chcete platiť kartou alebo v hotovosti?“ pýta sa.
„Chcela by som platiť kartou,“ odpovedám.
„V poriadku.“
„Bude to osemdesiatpäť korún,“ hovorí.
Vyťahujem svoju platobnú kartu.
