Barista sa na mňa usmieva.
Podržím kartu nad terminálom.
Prístroj zapípa.
„Chcete účtenku?“ pýta sa.
„Nie, ďakujem,“ odpovedám.
Prejdem k stene.
Vezmem si z háčika svoj hrubý zimný kabát.
Oblečiem si kabát.
Dám si aj šál.
Natiahnem si aj rukavice.
Teraz som pripravená na chlad.
Znovu sa pozriem na baristu.
„Veľmi pekne ďakujem za kávu,“ hovorím.
„Niet za čo,“ hovorí s úsmevom.
„Majte pekný deň.“
„Nápodobne,“ hovorím.
Prejdem k vchodovým dverám.
Potlačím ťažké dvere a otvorím ich.
Vietor je studený, ale cítim sa dobre.
