Kasper, Sara, Emil a ja sme hrali bedminton takmer dve hodiny.
Teraz sa zápas skončil a boli sme príjemne unavení.
Prešli sme k lavičke.
Spolu sme si sadli.
Otvorila som tašku a našla svoju fľašu s vodou.
Dlho sme len pili studenú vodu.
„To bol náročný zápas,“ povedal Kasper.
Sara sa usmiala a pozrela sa na mňa.
„Prišla si do Dánska v januári, však?“ spýtala sa.
„Áno, pricestovala som z Mexika v januári,“ odpovedala som.
Kasper položil svoju raketu na lavičku.
„Aké boli tvoje prvé dni v krajine?“ spýtal sa.
Zaspomínala som si na svoj prvý týždeň.
Všetko bolo vtedy nové a veľmi odlišné.
Vôbec som to mesto nepoznala.
„Bolo veľmi chladno,“ začala som.
Kasper a Sara sa nahlas zasmiali.
„Dánska zima je vždy chladná,“ povedala Sara.
Kasper sa ma spýtal.
„Aký bol tvoj úplne prvý deň?“
