Kasper chcel počuť o mojom úplne prvom popoludní.
Bolo chladné popoludnie v januári.
Vyšla som po schodoch k svojmu novému bytu.
Mala som jeden veľmi ťažký kufor.
Bola som veľmi unavená po dlhej ceste.
Svoj kufor som si sama odniesla hore a dovnútra.
O chvíľu neskôr som vyšla na schodisko.
Otvorili sa dvere vedľa mojich.
Vyšla von mladá žena a usmiala sa na mňa.
„Ahoj, volám sa Nina,“ povedala.
„Aj ja bývam tu v budove.“
Opätovala som úsmev a povedala svoje meno.
Nina bývala hneď vedľa mňa.
Trochu sme sa spolu porozprávali na schodisku.
Bolo milé hneď stretnúť susedu.
„Vitaj v Dánsku,“ povedala Nina.
Bol to môj prvý deň tu.
Bola som rada, lebo som už mala kamarátku.
