Kasper sa spýtal:
"A čo tvoja práca?"
Na chvíľu som sa zamyslela.
Potom sa Sara spýtala na môj prvý deň v softvérovej spoločnosti.
V to ráno som bola dosť nervózna.
Do práce som išla autobusom.
Pozerala som von oknom a myslela na svojich nových kolegov.
Vošla som do veľkej budovy.
Stála som v novej kancelárii a pozdravila.
Rýchlo ku mne podišiel nejaký muž.
"Vitaj v Dánsku, volám sa Peter," povedal milo.
Peter sa široko usmial a ukázal mi môj nový pracovný stôl.
Bol to môj nový kolega.
Vypili sme spolu šálku kávy.
Spýtal sa ma na moju dlhú cestu z Mexika.
Bolo to veľmi príjemné a uvoľnila som sa.
Sara prikývla a pozrela sa na mňa.
"Dobrí kolegovia sú nesmierne dôležití," povedala.
Úplne som súhlasila.
