Je sobota a ja oddychujem na pohovke.
Začínam videohovor so svojou rodinou v Mexiku.
Moja mama odpovedá takmer okamžite.
„Ahoj Maya, zlatko moje,“ hovorí so širokým úsmevom.
V pozadí vidím svoju sestru Sofíu, brata Diega a nášho psa Lolu.
„Ahoj, mami.“
„Ide to tu naozaj dobre,“ hovorím šťastne.
Trochu sa rozprávame o ich týždni doma v Mexiku.
Potom sa moja mama pýta, či bolo na začiatku niečo ťažké.
Spomínam si na svoje prvé dni v meste.
Všetko bolo nové a dni boli niekedy ťažké.
„Začiatok nebol vždy ľahký,“ hovorím jej.
„Celé dopoludnie som čakala v dlhom rade.“
„Sedela som v prázdnej kuchyni a chýbali ste mi.“
„Jednu sobotu som išla nesprávnym smerom a stratila som sa.“
„A spočiatku som nemala dosť teplú bundu,“ dodávam.
Moja mama pozorne počúva a prikyvuje.
Veľmi chce počuť všetky príbehy z mojich začiatkov v Dánsku.
Odpijem si z čaju a pokračujem v rozprávaní.
