Pozerám sa na mamu na obrazovke.
Chce počuť viac o dlhom rade.
Hovorím jej o dlhom dopoludní.
„Bol to chladný utorok v januári,“ hovorím.
Išla som autobusom do mestského klientskeho centra.
Vo veľkej miestnosti bolo naozaj veľa ľudí.
Vytiahla som si číslo z malého prístroja.
Moje číslo bolo päťdesiatdeväť.
Ale obrazovka na stene ukazovala len dvadsaťjeden.
Rad bol neuveriteľne pomalý.
Sedela som na tvrdej stoličke a čakala dve hodiny.
Často som pozerala hore na obrazovku.
Konečne milý muž vyvolal moje číslo.
Postavila som sa a podišla k jeho stolu.
Dala som mu svoj pas a dokumenty zo softvérovej firmy.
Prečítal si papiere a písal na počítači.
Konečne som dostala svoje CPR číslo.
Požiadal ma, aby som si na to dôležité číslo dávala naozaj dobrý pozor.
„Bola si veľmi trpezlivá,“ usmieva sa moja mama.
