Moja mama sa pýta, či som bola ten prvý večer v poriadku.
Byt bol zariadený, ale pre mňa stále nový.
V kuchyni som ešte nemala žiadne jedlo.
Cestou domov som si kúpila jednoduchú večeru.
Bol to sendvič z obchodu.
Sadla som si na malú pohovku.
V byte bolo veľmi ticho.
Potichu som zjedla svoju večeru.
Stále som poznala len svoju susedu Ninu.
„Ten večer ste mi všetci veľmi chýbali,“ hovorím jej.
Myslela som na svoju sestru Sofíu a brata Diega.
Dokonca mi chýbal aj náš pes Lola.
Ale tešila som sa na svoj nový život.
Moja mama si priloží ruku na srdce.
„Začiatok je vždy ťažký,“ odpovedá.
Prikývnem a spomínam na ten deň.
Bol to ťažký večer, ale nasledujúce ráno bolo oveľa lepšie.
