Zatváram počítač.
Videohovor s mojou rodinou sa skončil.
Usmievam sa a rozhliadam sa po obývačke.
Je tu teplo a útulne.
Mnohé veci sú teraz iné.
Myslím na svoje prvé dni v Dánsku.
Január bol veľmi chladný mesiac.
Prvé týždne boli veľkou výzvou.
Rodina mi veľmi chýbala.
Všetko v meste bolo pre mňa nové.
Moja susedka Nina ma privítala.
Teraz mám mäkkú pohovku a pekný koberec.
Každé ráno chodím do práce autobusom.
Rozprávam sa s Petrom a ostatnými kolegami.
Zima bola dlhá.
Ale v prvých mesiacoch som sa veľa naučila.
Už nie som v meste len hosťom.
Pozerám sa z okna.
Pijem zvyšok svojho čaju a som šťastná.
Cítim sa úplne ako doma.
