Je január a je veľmi chladno.
Kráčam domov z autobusovej zastávky v Kodani.
Na ulici vidím kvetinárstvo.
Vnútri je svetlo a teplo.
Vchádzam do teplého obchodu.
Pozerám sa na malú zelenú rastlinu.
Predavač sa na mňa usmieva.
"Dobrý deň," hovorí.
"Dobrý deň," hovorím.
"Hľadám nejakú rastlinu."
"Je to darček?" pýta sa.
"Nie, je to do mojej izby," odpovedám.
"Je to naozaj dobrá rastlina," hovorí.
"Koľko stojí?" pýtam sa.
"Stojí päťdesiatpäť korún," odpovedá.
Platím za svoju novú rastlinu.
Vkladá rastlinu do papierovej tašky.
"Nech sa páči, tu je vaša taška," hovorí.
"Veľmi pekne ďakujem," hovorím s radosťou.
Vychádzam do chladného večera.
Moja malá rastlina ma veľmi teší.
