Teraz som doma.
Tu je moja izba.
Je to malá izba.
Mám novú rastlinu.
Stojí na mojom písacom stole.
Je večer a je január.
Moje okno je veľmi tmavé.
Vonku je úplná tma.
Mám lampu a šálku čaju.
Zapínam svoju lampu.
Teraz je moja izba teplá a svetlá.
Môj čaj je tiež teplý.
Sedím za svojím písacím stolom.
Mám tu svoj počítač.
Otváram svoj počítač.
Teraz volám svojej rodine do Mexika.
Teším sa, že ich uvidím.
