Párkrát to zazvoní.
Obrazovka sa rozsvieti.
Vidím obývačku.
Svieti slnko a obývačka je veľmi svetlá.
Vidím dvoch ľudí.
Je to moja mama a môj otec.
Veľmi sa usmievajú a mávajú mi.
„Ahoj, mami a oci!“ hovorím nahlas.
„Ahoj, Maya,“ hovorí môj otec.
„Ako sa máš?“
„Mám sa dobre,“ odpovedám radostne.
Zrazu začujem zvuk.
Je to malé zaštekanie.
„Ach, počujem psa!“ hovorím a smejem sa.
Malý pes vyskočí na pohovku.
Pozrie sa do kamery.
„Tam je môj pes!“
„Ahoj, Lola,“ hovorím.
Lola vrtí chvostom.
„Áno, je to tvoj pes,“ hovorí moja mama s úsmevom.
Milujem svoju rodinu.
Je krásne vidieť ich všetkých.
