Teraz sú na mojej obrazovke dve nové tváre.
Je to moja mladšia sestra Sofía a môj starší brat Diego.
Smejú sa a trochu do seba strkajú.
"Ahojte, sestrička a braček!" hovorím radostne.
"Ahoj, Maya," hovorí Diego.
Môj brat má široký úsmev.
"Je v Dánsku zima?" pýta sa.
"Je to chladná zima?"
"Áno, je to veľmi chladná zima," smejem sa.
"Ale mám teplú izbu a šálku čaju."
Teraz Sofía dvíha pred obrazovku veľkú vec.
Je to veľká kniha.
"Máš tam novú knihu, Sofía?" pýtam sa.
"Áno, je to moja nová kniha," hovorí moja sestra hrdo.
"Je to kniha z mojej univerzity."
"Je to veľmi hrubá kniha!"
Usmievam sa na svojho brata a svoju sestru.
Chýba mi moja rodina v Mexiku.
Ale sú priamo tu na mojej malej obrazovke.
