Moja mama sa pozerá na obrazovku.
„Je to tvoja izba, Maya?“ pýta sa.
„Áno, to je moja izba,“ odpovedám.
„Ale je to dočasná izba.“
Zdvihnem svoj počítač.
Ukazujem svoju malú izbu rodine.
„Tu je posteľ,“ hovorím.
„A tu je moja nová rastlina.“
„Je to veľmi pekná rastlina,“ hovorí moja mama.
Otočím svoj počítač.
„A tu je okno,“ hovorím.
Moja sestra Sofía sa pozerá na moje okno.
„Ale je tam veľká tma,“ hovorí.
„Áno, vonku je úplne čierno,“ odpovedám.
„Ale v lete je tu veľa slnka.“
Je večer a je chladno.
„Ale mám svoju lampu,“ usmejem sa.
„Takže je to dobrá izba.“
