Pozerám sa na svoj počítač.
Trochu mi chýba môj domov v Mexiku.
„Oci, aká je tvoja záhrada?“ hovorím.
Môj otec sa na mňa usmieva.
Ide von s telefónom.
Je tam veľká záhrada.
Slnko tam veľmi svieti.
„Pozri, Maya,“ hovorí môj otec.
„Tu je záhrada a strom.“
Je to veľmi veľký strom.
Je to krásny strom.
Usmievam sa na svoju obrazovku.
Vo vnútri sa cítim dobre a je mi teplo.
Moja mama, moja sestra a môj brat idú tiež von.
Môj pes behá pod stromom.
Celá moja rodina mi máva.
„Ahojte všetci!“ hovorím.
„Ahoj, Maya,“ hovoria.
Zatváram svoj počítač.
