Je január v Kodani.
Stojím vo svojej dočasnej izbe.
Dnes sa sťahujem do nového bytu.
Je v tej istej budove.
Môj veľký kufor stojí na podlahe.
Zatváram ho.
Poslednýkrát sa rozhliadam po izbe.
Pozerám sa pod malú posteľ.
Pod posteľou leží kniha.
Je z Mexika.
Dávam knihu do tašky.
Otváram skriňu.
V skrini je pár topánok.
Beriem topánky.
Teraz v skrini nie je nič.
Idem k písaciemu stolu pri okne.
Na stole leží kábel.
Beriem kábel.
Dávam kábel do tašky.
Beriem svoje dve tašky.
Zhasínam svetlo a zatváram dvere.
