Idem hore schodmi.
V rukách mám dve tašky.
Konečne som pri svojich nových dverách.
Vo vrecku mám kľúč.
Položím tašky na podlahu.
Vyberiem kľúč.
Odomknem dvere.
Potlačím dvere a vojdem dnu.
Byt je malý, ale je dokonalý.
Má pekný, svetlý nábytok.
Pozriem sa do obývačky.
Pri okne stojí pohovka.
Pod pohovkou je koberec.
Na pohovke leží malý vankúš.
V rohu stojí lampa.
Zatvorím za sebou dvere.
Položím svoj kľúč na stôl.
