Znova vychádzam na schodisko.
Môj najväčší kufor stojí na podlahe.
Je veľmi ťažký.
Ťahám za kufor.
Zrazu počujem na schodoch kroky.
Je to moja dánska susedka Nina.
Vrúcne sa na mňa usmieva.
„Sťahuješ sa dnes, Maya?“ pýta sa.
„Áno, konečne som vo svojom novom byte,“ hovorím.
„Pomôžem ti,“ hovorí Nina milo.
Chytí kufor.
Spolu nesieme kufor do obývačky.
Nina ho opatrne položí na podlahu.
Teraz kufor stojí pri veľkom okne.
Pod oknom už leží taška.
„Veľmi pekne ďakujem za pomoc, Nina,“ hovorím radostne.
„Niet za čo,“ usmieva sa.
Nina vychádza na schodisko.
Zatváram dvere a pozerám sa na kufor pri okne.
