Vyjdem do malej kuchyne.
Moja cestovná taška stojí na podlahe.
Otvorím tašku.
V taške je veľa vecí.
Moje obľúbené hrnčeky ležia v taške.
Vyberiem hrnčeky.
Nad kuchynskou linkou je skrinka.
Vložím hrnčeky do skrinky.
Teraz stoja na polici.
Mám aj červenú rýchlovarnú kanvicu.
Leží v taške pod hrubým svetrom.
Vyberiem rýchlovarnú kanvicu.
Položím ju na kuchynskú linku.
Teraz stojí červená rýchlovarná kanvica hneď pri dreze.
V taške leží aj škatuľka čaju.
Vezmem škatuľku a položím ju k rýchlovarnej kanvici.
Teraz je kuchyňa takmer pripravená.
Teším sa, že si neskôr dám šálku čaju.
