Idem do obývačky.
Pri okne je malý písací stôl.
Ten stôl je na moju prácu.
Tu môžem v pokoji pracovať.
Je to pekné malé miesto.
Otváram svoju tašku.
Vyberám svoj počítač.
Teraz je na stole.
Na stole je aj lampa.
Lampa stojí hneď pri počítači.
Má teplé svetlo.
Na stole leží aj malá kniha.
Mám malú čiernu tašku s káblami.
Leží pod písacím stolom.
Takto tá taška nezavadzia.
Pri písacom stole je dobrá stolička.
Sedím na stoličke a pozerám sa.
Otváram počítač a začínam písať.
