Vojdem do spálne.
Prinesiem kufor z obývačky.
Otvorím kufor.
Vyberiem svoje oblečenie.
Poskladám oblečenie.
Uložím ho do skrine.
Teraz moje svetre ležia v skrini.
V izbe je veľká posteľ.
Na posteli leží hrubá deka.
Deka je z Mexika.
Nájdem aj pár papúč.
Sú veľmi mäkké.
Pri stene stojí malá stolička.
Položím svoje papuče na podlahu.
Teraz ležia pod stoličkou.
Teraz je kufor prázdny.
Zatvorím ho a dám ho pod posteľ.
