Vyjdem na chodbu.
Moja nová rastlina stojí na podlahe.
Je to malá zelená rastlina.
Vezmem rastlinu.
Odnesiem ju do obývačky.
V obývačke je veľké okno.
Položím rastlinu na parapet.
Urobím krok dozadu.
Teraz rastlina stojí v okne.
Zimné slnko svieti.
Rastlina stojí dokonale v bledom svetle.
Idem do kuchyne.
Pod drezom stojí malá krhla.
Vezmem krhlu.
Polejem svoju novú rastlinu.
Pri kvetináči ležia dva uschnuté listy.
Odstránim listy.
Hodím ich do koša.
Položím krhlu na podlahu k oknu.
Slnko svieti na mokré zelené listy.
