Byt je konečne hotový.
Teraz je to skutočný domov.
Nina klope na dvere.
Stojí pri dverách s teplým jedlom.
„Mám so sebou dve pizze,“ hovorí.
Ideme do obývačky.
Pri okne stojí malá pohovka.
Sedíme spolu na pohovke.
Na konferenčnom stolíku ležia dve škatule od pizze.
Škatule ležia medzi nami.
Na stole stoja aj dva poháre.
Jeme teplé pizze.
„Vitaj vo svojom novom byte,“ hovorí Nina.
„Veľmi pekne ďakujem,“ odpovedám.
Dlho sa spolu rozprávame.
Moja nová rastlina stojí v okne.
Moje papuče ležia pod stoličkou.
Všetko je na svojom mieste.
Som veľmi spokojná so svojím novým domovom.
