Je pondelok ráno a ja sedím v autobuse.
Som na ceste do práce.
Pozerám sa z okna.
Dnes som trochu nervózna.
Ale tiež sa na to veľmi teším.
Dnes sa začína veľký nový softvérový projekt.
Vo firme pracujem ako softvérová inžinierka od januára.
Dobre poznám svojho kolegu Petra.
Pracujeme spolu od môjho prvého dňa.
Ale teraz musím úzko spolupracovať s celým tímom.
Budem spolupracovať s naším šéfom, našou dizajnérkou a naším testerom.
Vo firme pracujú už dlho.
Autobus zastavuje a nastupujú ďalší ľudia.
Pozerám sa na hodinky.
Je osem hodín.
Ranná porada sa začína o pol hodiny.
Zhlboka sa nadýchnem.
Som pripravená na nový projekt.
