Sedíme v zasadacej miestnosti.
Je čas na našu krátku rannú poradu.
Rozhliadam sa po svojich kolegoch.
Dnes je pre mňa výnimočný deň.
Postavím sa.
Som softvérová inžinierka a budem prezentovať svoju časť projektu.
Trochu sa mi trasú ruky.
Ale dobre som sa pripravila.
"Dobré ráno," poviem nahlas.
"Pracovala som na technickom pláne," hovorím im.
"Prečítala som všetky dokumenty."
"A napísala som si poznámky k úlohám tohto týždňa."
Vysvetľujem plán celému tímu.
Vlastne nie je ťažké hovoriť o technike.
Peter sedí oproti mne.
Cítim, že sa viac uvoľňujem.
Počúva a prikyvuje.
Končím svoju prezentáciu a ostatní sa usmievajú.
Moja prvá prezentácia v práci dopadla dobre.
