Je ďalší deň v kancelárii.
Sedím vedľa Madsa, nášho softvérového testera.
Pozerá na nové obrazovky.
Veľmi rýchlo kliká myšou.
Zrazu sa zastaví.
Už našiel malú chybu.
Pozerá sa na mňa a trochu sa smeje.
"Mojou prácou je kaziť veci," hovorí.
"Musím nájsť chyby pred našimi používateľmi."
Pracuje ako tester päť rokov.
Testoval mnoho rôznych projektov.
Preto nachádza problémy tak rýchlo.
Pozerám sa na chybu na svojom počítači.
Našťastie je to len malý problém.
Kód hneď opravím.
Ešte raz otestuje program.
Teraz všetko funguje úplne perfektne.
Som veľmi rada za jeho pomoc.
