Je streda večer.
Som v posilňovni na svojej pravidelnej hodine.
Dnes dvíham činky.
Moje ruky sú unavené, ale je to príjemné.
Myslím na posledných pár dní.
Bol to veľmi rušný týždeň.
Úzko som spolupracovala s celým tímom.
Veľa som sa naučila o ich rôznych povolaniach.
Sedela som veľa hodín pri počítači.
Tento týždeň som napísala veľa nového kódu.
Mala som svoju prvú prezentáciu pred tímom.
Bolo to trochu náročné, ale aj zábavné.
Lepšie som spoznala svojich nových kolegov.
V kancelárii sa cítim čoraz lepšie.
Tréning je po dlhom dni veľmi príjemný.
Je dobré rozhýbať si telo.
Tento tréning som si naozaj zaslúžila.
Položím činky na zem a napijem sa trochu vody.
Usmejem sa na seba do zrkadla.
Konečne som skutočnou súčasťou tímu.
