Konečne je piatok a rušný týždeň je takmer za nami.
Spolu obedujeme v svetlej jedálni.
Sedím pri veľkom stole spolu s mojím tímom.
Peter, naša dizajnérka Eva a náš tester Mads sú tu tiež.
Všetci sme unavení, ale sme veľmi šťastní.
Nový projekt bol vzrušujúci.
„Pracovali sme naozaj tvrdo,“ hovorí Peter a usmieva sa.
„Áno, vyriešili sme veľa zložitých problémov,“ odpovedám.
Ako softvéroví inžinieri sme tento týždeň napísali veľa kódu.
„A ja som to všetko otestoval,“ smeje sa Mads.
„Našťastie si nenašiel veľa chýb,“ podpichuje Peter.
Eva nám na svojom telefóne ukazuje svoj krásny dizajn.
Ako dizajnérka pracuje už mnoho rokov.
Rozprávame sa o našich rôznych úlohách, kým jeme.
Je príjemné lepšie spoznať svojich kolegov.
Stali sme sa naozaj dobrým tímom.
Odhryznem si z jedla a pozriem sa na nich.
Teším sa na pokračovanie projektu s nimi.
