Je sobota ráno.
V Dánsku je zima.
Počasie je dnes veľmi chladné.
Stojím na veľkom námestí v meste.
Je tu vonkajší trh.
Pozerám sa na tie mnohé stánky.
Všetky vyzerajú lákavo.
Na námestí je veľa ľudí.
Ľudia majú na sebe teplé zimné oblečenie.
Mám na sebe len tenkú bundu.
Mám so sebou veľkú tašku.
Taška je práve teraz úplne prázdna.
Hľadám čerstvé jedlo na víkend.
Trh má veľa čerstvého tovaru.
Vidím zeleninu, ovocie a chlieb.
Rozmýšľam nad cenami.
Koľko tu stoja veci?
Idem k prvému stánku.
