Podídem k stánku so zeleninou.
Dnes varím teplú polievku.
Pozerám sa na množstvo zeleniny na stole.
Ukazujem na nejaké veľké zimné mrkvy.
Potrebujem mrkvy do svojej polievky.
Za stolom stojí predavač.
„Dobrý deň,“ hovorí.
„Dobrý deň,“ odpovedám.
„Koľko stoja tie mrkvy?“ pýtam sa.
„Stoja pätnásť korún za kilo,“ odpovedá predavač.
Pätnásť korún je dobrá cena.
„Vezmem si jedno kilo, prosím,“ hovorím.
Predavač váži mrkvy.
Dáva ich do papierového vrecka.
Podáva mi vrecko.
Platím tých pätnásť korún.
Dávam si vrecko do svojej veľkej tašky.
Teším sa na teplú polievku.
