Predo mnou je veľký stánok so syrom.
Stánok má veľa veľkých syrov.
Milý predavač sa na mňa usmieva.
Má malý kúsok syra na drevenej paličke.
"Nech sa páči, malá ochutnávka," hovorí.
Dáva mi paličku.
Jem ten žltý syr.
Chutí naozaj dobre.
Pozerám sa na malý syr.
"Koľko stojí tento syr?" pýtam sa.
"Stojí päťdesiatpäť korún," odpovedá predavač.
To je dobrá cena.
Ukazujem na ten malý syr.
"Kúpim si ho," hovorím.
Balí syr do papiera.
Dávam mu peniaze.
"Ďakujem veľmi pekne," hovorí.
Syr vonia výrazne a dobre.
