Dnes je na trhu veľa ľudí.
Nájdem malý stánok s ovocím.
V stánku je veľa košíkov.
Košíky sú plné tmavočervených zimných jabĺk.
Pozerám sa na malé vrecko s jablkami.
„Koľko stojí malé vrecko?“ pýtam sa predavača.
Pozrie sa do košíka.
„Cena je dvadsať korún,“ odpovedá.
Hľadám v taške peniaze.
Dám mu päťdesiatkorunovú bankovku.
Predavač mi podá vrecko s jablkami.
Potom mi vráti peniaze.
Dostanem naspäť presne tridsať korún v minciach.
Mince sú hrubé a ťažké.
Vložím si ťažké mince do vrecka na kabáte.
Jablká voňajú veľmi čerstvo.
Vložím vrecko do svojej veľkej nákupnej tašky.
