Idem k východu z trhu.
Vidím veľký kvetinový stánok.
V stánku je veľa krásnych kvetov.
Zastavím sa pred stánkom.
Pozerám sa na zväzok zimných tulipánov.
Sú veľmi farebné.
Ukážem na tulipány.
„Koľko stoja tulipány?“ pýtam sa predavača.
Predavač zdvihne tulipány.
„Stoja štyridsať kroner,“ odpovedá.
„Kúpim si ich,“ hovorím.
Platím za kvety.
Predavač mi dáva tulipány.
Teraz som na trhu skončila.
Idem späť do svojho bytu.
V ruke držím farebné tulipány.
Pijem svoju horúcu kávu.
Slnko svieti nad rušným trhom.
