Je piatok popoludní a skončila som v práci.
Kráčam po ulici a zastavím sa v kvetinárstve.
Mám v pláne kúpiť darček pre Evu.
Otvorím dvere a vojdem do malého obchodu.
„Dobrý deň,“ hovorí predavač so širokým úsmevom.
„Dobrý deň,“ odpovedám.
Pozerám sa na to množstvo krásnych kvetov.
Myslím si, že Eva má vždy rada farby.
Je dizajnérka, takže si asi zamiluje niečo farebné.
Nájdem veľkú kyticu so žltými tulipánmi.
„Rada by som si kúpila túto kyticu,“ hovorím a ukazujem na tulipány.
„To je naozaj dobrý výber,“ hovorí predavač.
Zabalí kvety do pekného papiera.
„Bude to stopäťdesiat korún,“ hovorí.
Vytiahnem kartu a zaplatím za kvety.
„Dnes večer idem na večeru,“ hovorím mu.
„Tak to sa vaša kamarátka určite poteší,“ odpovedá.
Vezmem si kyticu a vyjdem z obchodu.
Teraz už len musím nájsť svoju autobusovú zastávku.
