Eva nalieva kávu do dvoch veľkých šálok.
Sadáme si na mäkkú pohovku v obývačke.
„Ako sa ti teraz darí v meste?“ pýta sa Eva.
Odpijem si z teplej kávy.
Hovorím jej, že mám pocit, že môj nový život je vlastne naozaj krásny.
„Konečne som sa tu dobre zabývala,“ hovorím s úsmevom.
„Som rada, že to počujem,“ odpovedá.
„Tiež veľmi tvrdo pracuješ na našom projekte v kancelárii.“
„Áno, ale teraz si plánujem brať viac voľna,“ hovorím.
„Cez víkendy si budem mesto užívať oveľa viac.“
„To dobre chápem,“ hovorí Eva.
Dlho sa rozprávame o našich ďalších kolegoch a práci.
Smejeme sa a zdieľame mnoho príbehov.
Usmievam sa na ňu ponad šálku kávy.
Hovorím, že dúfam, že sa budeme naďalej vídať mimo práce.
„To určite budeme,“ odpovedá radostne.
Myslím si, že spolu asi zažijeme veľa zábavných večerov.
