Vstanem a vezmem si bundu.
Je neskoro a musím ísť domov autobusom.
Eva ma odprevádza k dverám.
„Podnikneme niečo budúci mesiac?“ pýta sa zrazu.
„Mám v pláne ísť do múzea umenia,“ vysvetľuje.
„Chceš sa možno pridať?“
Nadšene prikývnem a vezmem si tašku.
„Áno, veľmi rada,“ odpovedám.
Verím, že sa určite zabavíme.
Tiež jej hovorím, že milujem moderné umenie.
„A cítim, že sa nám spolu vždy tak dobre rozpráva,“ dodávam.
Eva sa široko usmeje a otvorí mi vchodové dvere.
„Určite niečo čoskoro naplánujeme,“ sľubuje.
„V pondelok ti pošlem správu,“ hovorím.
Objímem ju a vyjdem na schodisko.
Už teraz sa teším na náš výlet do múzea.
