Vonku je stále tma.
Ráno sa budím pomaly.
Chvíľu ležím v posteli.
Dnes je úplne obyčajný všedný deň.
Teraz vstávam z postele.
Podlaha je pod mojimi nohami trochu studená.
Idem rovno do kúpeľne.
V kúpeľni púšťam vodu.
Voda je teplá a príjemná.
Vstupujem do sprchovacieho kúta.
Tu si dávam príjemnú teplú sprchu.
Najprv si umývam vlasy šampónom.
Potom sa umývam mydlom.
Mydlo vonia sviežo po citrusoch.
Teplá voda ma prebúdza.
Nakoniec vypínam sprchu.
Beriem si mäkký uterák.
Teraz sa dôkladne utieram.
Som úplne zobudená a pripravená na dnešný deň.
