Vonku na ulici čakám na svoj autobus.
Dnes je chladno.
Na zastávke stojí veľa ľudí.
Prichádza červený autobus.
Dvere sa otvárajú.
Nastupujem do autobusu.
Tu si skenujem cestovnú kartu.
Vodič autobusu sa na mňa pozerá.
"Dobré ráno," hovorí vodič.
"Dobré ráno," odpovedám.
Prechádzam autobusom.
Nájdem si voľné miesto pri okne.
Sadnem si.
Autobus prechádza mestom.
Za oknom vidím veľa ľudí.
Rýchlo bicyklujú po cyklistickom chodníku.
Prechádzame okolo krásneho parku.
V parku sa prechádzajú ľudia.
Teraz autobus zastavuje pri mojom pracovisku.
Vystupujem a idem do kancelárie.
