Prichádzam do svojej práce.
Pracujem v softvérovej spoločnosti.
Vchádzam do veľkej miestnosti.
Môj stôl stojí pri okne.
Tu si sadám na svoju stoličku.
Zapínam svoj počítač.
Obrazovka sa rozsvieti.
Najprv si čítam svoje správy.
Mám e-mail od svojho manažéra.
E-mail sa týka môjho nového projektu.
Píšem krátku odpoveď.
Potom otváram svoj pracovný program.
Teraz píšem kód pre projekt.
Kód zapĺňa celú obrazovku.
Rýchlo píšem na svojej klávesnici.
Veľmi sa sústredím na kód.
Práca je pútavá.
Pijem trochu vody zo svojej fľaše.
Som veľmi spokojná so svojou novou prácou v Kodani.
