V kancelárii je neskoré popoludnie.
Pozerám sa na svoju obrazovku.
Píšem posledný kód.
Teraz je úloha hotová.
Usmievam sa.
Zatváram svoj počítač.
Dávam ho do tašky.
Potom si balím svoje veci.
Postavím sa.
Môj kolega Peter sedí za svojím stolom.
Idem k nemu.
"Dovidenia, Peter," hovorím.
"Dovidenia, Maya," hovorí Peter.
"Prajem pekný večer," hovorí.
"Ďakujem, nápodobne," odpovedám.
Vychádzam z kancelárie.
Vonku na chodbe idem výťahom dole.
Nakoniec vychádzam z budovy.
Teraz idem domov.
