Som doma vo svojom byte.
V kuchyni pripravujem večeru.
Umývam čerstvú zeleninu.
Na doske krájam cibuľu.
Krájam aj dve červené paradajky.
Beriem si panvicu.
Na sporáku zohrievam trochu oleja.
Dávam zeleninu na panvicu.
Opekám jedlo.
Vonia to naozaj dobre.
Do jedla dávam soľ a korenie.
Jedlo je hotové.
Beriem si tanier.
Dávam jedlo na tanier.
Idem si po pohár vody.
Sadám si za stôl.
Jem svoju večeru.
Jedlo chutí výborne.
Vychutnávam si pokojné jedlo.
