Lietadlo je teraz v Kodani.
Je január.
Som veľmi nadšená.
Balím si knihu do tašky.
Vedľa mňa je cestujúci.
Pozerá sa na mňa a usmieva sa.
„Ahoj,“ hovorí.
„Ahoj,“ hovorím.
„Ako sa voláš?“ pýta sa.
„Volám sa Maya,“ hovorím.
„Odkiaľ pochádzaš, Maya?“ pýta sa.
Radostne sa usmievam.
„Pochádzam z Mexika,“ odpovedám.
„Si z Dánska?“ pýtam sa.
„Áno, som z Dánska,“ hovorí.
„Vitaj v Dánsku,“ hovorí.
„Veľmi pekne ďakujem,“ hovorím.
Teraz sme tu.
Som pripravená.
