Teraz som vonku.
Môj kufor je veľký a ťažký.
Tam je taxík.
Dvíham svoj kufor do taxíka.
Vodič je priateľský muž.
„Aká je adresa?“ pýta sa.
„Je to Parkvej číslo dvanásť,“ hovorím.
Prikývne a ide.
„Ste turistka?“ pýta sa vodič.
„Nie, nie som turistka,“ odpovedám.
„Odkiaľ pochádzate?“ pýta sa.
„Pochádzam z Mexika,“ hovorím.
Pozerám sa z okna.
Som veľmi hrdá.
„Som softvérová inžinierka,“ hovorím.
„Moja nová práca je tu v Kodani.“
Usmeje sa.
„Aké vzrušujúce.“
„Veľa šťastia v Dánsku,“ hovorí.
„Veľmi pekne ďakujem,“ hovorím.
