Teraz som v obývačke.
Je tu malá pohovka.
Volám mame do Mexika.
„Ahoj, mami,“ hovorím.
„Ahoj, Maya,“ hovorí moja mama.
„Kde si?“ pýta sa.
„Som v Kodani,“ odpovedám.
„Teraz som v byte.“
„To je veľmi dobre,“ hovorí moja mama.
„Je veľký?“ pýta sa.
„Nie, je malý,“ odpovedám.
„Ale je útulný a som šťastná.“
„Je tam zima?“ pýta sa.
„Áno, vonku je zima,“ hovorím.
„Ale tu je teplo.“
„Som v bezpečí.“
„To je dobre,“ hovorí moja mama.
Usmievam sa.
Dánsko je môj nový domov.
