Otváram svoje dvere.
Stojím na schodisku.
Je tu ticho.
Otvárajú sa dvere.
Nejaká žena sa na mňa usmieva.
„Ahoj,“ hovorí.
„Ako sa voláš?“ pýta sa.
„Volám sa Maya,“ odpovedám.
„Odkiaľ pochádzaš?“ pýta sa.
„Pochádzam z Mexika,“ hovorím.
„Vitaj v dome,“ hovorí žena.
„Volám sa Nina,“ hovorí.
„Som tvoja susedka.“
Nina je veľmi priateľská.
Hovorí pomaly a zreteľne.
„Tu sú moje dvere,“ hovorí.
„Rada pomôžem.“
„Stačí len zaklopať,“ hovorí Nina.
„Veľmi pekne ďakujem, Nina,“ odpovedám.
Som veľmi šťastná.
Teraz mám v Kodani kamarátku.
