Teraz je noc.
Je to moja prvá noc v Kodani.
Som v kúpeľni.
Je veľmi malá.
Je tam umývadlo.
Moja zubná kefka je červená.
Dávam si zubnú pastu na kefku.
Čistím si zuby.
Voda je studená.
Umývam si tvár.
Utieram si tvár.
Idem k svojej posteli.
Posteľ je úzka.
Ale je teplá a mäkká.
Teraz ležím pod paplónom.
Môj telefón leží na stole.
Nastavujem si budík.
Zazvoní zajtra o ôsmej.
Som unavená, ale som pripravená.
Dobrú noc, Kodaň.
