Budím sa skoro.
Je len šesť hodín.
Je nový deň.
Pomaly vstávam.
Idem k oknu.
Pozerám sa von na mesto.
Vonku je stále tma a chladno.
Zima je stále tu.
Idem do kúpeľne.
Umývam si tvár.
Umývam si zuby.
Potom sa obliekam.
Obliekam si hrubý, teplý sveter.
Je perfektný na chladný deň.
Idem do kuchyne.
Robím si šálku teplej kávy.
Jem krajec chleba so syrom.
Teraz som úplne prebudená.
Som pripravená na nový deň.
