Vychádzam na ulicu.
Je to bežné ráno.
Idem dole k zastávke.
Stojí tam veľa ľudí.
Tiež čakajú na autobus.
Pozriem sa dole cestou.
Prichádza veľký červený autobus.
Je to autobus číslo päť.
Autobus predo mnou zastaví.
Dvere sa otvoria.
Nastúpim do autobusu.
V taške si nájdem cestovnú kartu.
Naskenujem modrú kartu na prístroji.
Prístroj pípne.
Prejdem do zadnej časti autobusu.
Nájdem si voľné miesto pri okne.
Sadnem si.
Pozerám sa na ľudí na ulici.
Prechádzame rušnými ulicami.
Som pripravená na nový pracovný deň.
