Prichádzam do kancelárie.
Je to veľká softvérová firma.
Vchádzam dnu.
Môj kolega Peter je už tam.
Je veľmi priateľský.
„Dobré ráno, Maya,“ hovorí Peter.
„Dobré ráno, Peter,“ hovorím.
Idem na svoje miesto.
Sedím za svojím stolom.
Zapínam svoj počítač.
Mám šálku kávy.
Je čierna a horúca.
Pijem kávu.
Pracujem ako softvérová inžinierka.
Pozerám sa na obrazovku.
Píšem kód na svojom počítači.
Práca je veľmi zaujímavá.
Som spokojná so svojou prácou.
