Je dvanásť hodín.
Je čas na obed.
Peter a ja ideme dole do jedálne.
Jedáleň je veľká a svetlá.
Sme veľmi hladní.
Pozeráme sa na dobré jedlo.
Dnes je veľa možností.
Vyberám si klasický obložený chlebíček.
Je s rybou a citrónom.
Peter si berie veľký šalát.
Ideme k pokladni.
Pri pokladni stojí milý muž.
„Bude to štyridsať korún,“ hovorí mi.
Platím kartou.
„Nech sa páči,“ hovorím.
„Ďakujem a dobrú chuť,“ odpovedá.
Nachádzame voľný stôl v rohu.
Sadáme si.
Jedlo chutí naozaj dobre.
Rozprávame sa o našom dni.
