Skončila som v práci.
Vychádzam na veľké námestie.
V meste je dnes veľa ľudí.
Pristúpi ku mne jeden muž.
Má veľký fotoaparát.
Je to turista.
Usmeje sa a povie ahoj.
„Kde je múzeum?“ pýta sa turista.
To múzeum dobre poznám.
Nie je to ďaleko.
Ukážem dole ulicou.
„Pôjdete rovno,“ vysvetľujem.
„Potom odbočíte doľava.“
„Múzeum je na pravej strane.“
„Veľmi pekne ďakujem za pomoc,“ hovorí muž.
„Niet za čo,“ odpovedám veselo.
Kráča dole ulicou.
Kráčam ďalej smerom k pekárni.
