Prichádzam k malej pekárni na rohu.
Vchádzam do teplého obchodu.
Krásne to tu vonia po káve a koláčoch.
Za pultom stojí pekár v bielej zástere.
„Dobré popoludnie,“ hovorí pekár.
„Ako vám môžem pomôcť?“ pýta sa.
Pozerám sa na množstvo koláčov.
Kupujem koláč na dnešný večer.
Ukazujem na pekný čokoládový koláč.
„Prosila by som si ten čokoládový koláč,“ hovorím.
„Samozrejme,“ odpovedá pekár.
Vkladá koláč do bielej škatule.
„Bude to šesťdesiatpäť korún,“ hovorí.
Vyberám peňaženku z tašky.
Platím šesťdesiatpäť korún.
„Veľmi pekne ďakujem a prajem pekný večer,“ hovorí pekár.
„Ďakujem, aj vám,“ odpovedám.
Beriem si bielu škatuľu.
Opatrne vychádzam z obchodu s koláčom.
