Stojím na zastávke autobusu so svojím koláčom.
Červený autobus rýchlo prichádza.
Nastupujem a nachádzam si miesto.
Autobus prechádza mestom.
Cesta nie je dlhá.
Čoskoro sme na mojej ulici.
Vystupujem z autobusu.
Večerný vzduch je teraz trochu chladný.
Ale mám na sebe svoj teplý sveter.
Kráčam po ulici.
Budovy už teraz dobre poznám.
Tu je moja budova.
Vo svojej taške nachádzam kľúče.
Odomykám ťažké vchodové dvere.
Vchádzam na schodisko.
Je tu ticho a pokoj.
Odomykám svoje vlastné dvere a vchádzam dnu.
Odkladám si tašku do predsiene.
Teraz som doma vo svojom vlastnom meste.
