Je nedeľa ráno.
Slnko svieti dovnútra cez okno v mojom byte.
Idem do kuchyne.
Uvarím si kanvicu čerstvej kávy.
Vôňa kávy je toto ráno fantastická.
Na stene mám kalendár.
Obrátim stranu na ďalší mesiac.
Teraz je júl.
Do Kodane som sa presťahovala v januári.
Prišla som sem presne pred šiestimi mesiacmi.
Čas plynie naozaj rýchlo.
Môj prvý deň v tomto meste bol veľmi chladný.
Ale dnes je počasie teplé a krásne.
Chcem osláviť toto malé výročie.
Dnes nemám žiadne pevné plány.
Vezmem si šálku kávy a pozerám sa von na ulicu.
Chcem ísť von a preskúmať mesto vlastným tempom.
Teším sa na to, ako si vychutnám tieto svetlé hodiny.
