Idem sa prejsť cez veľké námestie v meste.
Každú nedeľu je tu veľký blší trh.
Slnko svieti a pomedzi stoly sa prechádza veľa ľudí.
Zastavím sa pri malom stole s množstvom rôznych vecí.
Za stolom stojí priateľský predavač.
Zrazu zbadám dva modré keramické taniere.
Zdvihnem ich a pozorne si ich prezerám.
„Koľko stoja tieto taniere?“ pýtam sa predavača.
Predavač sa na mňa usmeje.
„Stoja len štyridsať korún,“ odpovedá.
To je naozaj dobrá cena.
Pred mesiacom som si kúpila malý stôl do kuchyne.
Tieto taniere sa k tomuto stolu budú perfektne hodiť.
„Veľmi rada by som si ich kúpila,“ hovorím.
Dám predavačovi štyridsať korún a opatrne vložím taniere do tašky.
Vždy je príjemné nájsť niečo výnimočné v pokojnú nedeľu.
