Idem ďalej po trhu a zastavujem sa pri stánku s oblečením.
Vidím ťažký zimný kabát z vlny.
Tento kabát je krásny, ale veľmi hrubý.
Aj tak si ten kabát skúšam.
Je neskutočne teplý.
Okamžite si ho znova vyzliekam.
Je júl a dnes svieti slnko.
Za stolom stojí milá žena a usmieva sa.
„Je príliš teplý?“ pýta sa žena.
„Áno, na leto je trochu príliš teplý,“ odpovedám a smejem sa.
Dotýkam sa hrubej látky.
„Ale pred piatimi mesiacmi som tento zimný kabát naozaj potrebovala!“ hovorím.
Žena sa nahlas smeje.
„Áno, február bol veľmi chladný,“ hovorí.
Spomínam si na svoje prvé týždne v Kodani.
Vtedy som neustále mrzla.
Našťastie práve teraz nepotrebujem také teplé oblečenie.
Vešiam kabát späť na stojan a hovorím dovidenia.
