Kráčam preč od trhu a nachádzam malé miestne múzeum.
Vchádzam do tichej budovy.
Podídem k pultu, aby som si kúpila vstupenku.
Za pokladňou stojí mladý muž.
„Dobrý deň, jeden lístok pre dospelého, prosím,“ hovorím.
„Bude to sto korún,“ hovorí a vytlačí ho.
Zaplatím a pozerám sa na tieto pestrofarebné brožúry na pulte.
Propagujú špeciálnu výstavu o histórii mesta.
„Platí tento lístok aj na výstavu na poschodí?“ pýtam sa.
„Áno, toto múzeum má iba jeden spoločný lístok,“ odpovedá.
„Výstava je hore na prvom poschodí,“ hovorí.
„Môžete si tam hore pokojne dopriať dostatok času.“
„Je na nej veľa starých fotografií mesta,“ vysvetľuje.
„Niektoré z nich majú vyše sto rokov.“
„To znie naozaj zaujímavo,“ hovorím.
„Veľmi pekne ďakujem,“ usmievam sa.
Vezmem si lístok a pokojne kráčam hore schodmi.
