Sedím v múzejnej kaviarni a dávam si prestávku.
Pijem šálku kávy a oddychujem.
Vyberám z tašky modré taniere.
Tieto taniere sa perfektne hodia do mojej kuchyne.
Fotím si ich telefónom.
Posielam fotku svojej sestre Sofíi.
„Len sa pozri na tieto krásne taniere,“ píšem.
„Našla som ich na trhu pred hodinou.“
Sofía mi odpovedá takmer okamžite.
Posiela mi naspäť starú fotku.
Táto správa ma veľmi teší.
Fotka zachytáva nás dve na veľkom blšom trhu v Mexiku.
„Pamätáš si na tento trh?“
Sofía sa pýta v ďalšej správe.
„Boli sme tam presne pred dvoma rokmi!“ píše.
Pozerám sa na naše šťastné tváre na fotke.
Pripadá mi to, akoby to bolo veľmi dávno.
Pred dvoma rokmi som ešte žila v Mexiku.
Usmievam sa a píšem naspäť veselú správu.
