Kráčam domov cez veľký park.
Pred hodinou som bola v múzeu.
Teraz si chcem len užiť dobré počasie.
Zastavujem sa pri malom stánku, aby som si kúpila zmrzlinu v kornútku.
„Nech sa páči, tu je vaša zmrzlina,“ hovorí muž v stánku.
„Veľmi pekne ďakujem,“ odpovedám a beriem si zmrzlinu.
Pomaly kráčam pozdĺž jazera v parku.
Táto zmrzlina v kornútku vyzerá naozaj dobre.
Zrazu nad sebou počujem hlasný zvuk.
Veľká čajka letí strmhlav priamo na mňa.
Chce mi ukradnúť zmrzlinu!
Rýchlo sa prikrčím a chránim si zmrzlinu rukou.
Ten vták mi jedlo neukradne.
Čajka preletí okolo a pristane na tráve.
Žena na lavičke sa smeje.
„Dnes sú veľmi drzé,“ hovorí.
„Áno, to rozhodne sú,“ odvetím so smiechom.
Rýchlo dojem zmrzlinu, zatiaľ čo kráčam ďalej.
