Som späť vo svojom byte.
Je nedeľa večer a je tu veľmi ticho.
Stojím v kuchyni.
Umývam svoje nové taniere v dreze.
Tieto taniere sú naozaj krásne.
Sú modré a trochu ťažké.
Utieram ich kuchynskou utierkou.
Potom ich odkladám do skrinky.
Idem do obývačky a pozerám sa z okna.
Slnko pomaly zapadá nad strechami mesta.
Tento letný večer je krásny a svetlý.
Mám veľmi rada túto štvrť.
Bývam tu už pol roka.
Od januára sa toho toľko stalo.
Vtedy som v meste nikoho nepoznala.
Teraz poznám ulice a každodenný život oveľa lepšie.
V tomto meste sa cítim úplne ako doma.
Zajtra je pondelok a do práce idem autobusom.
Ale práve teraz len oddychujem.
Som úplne spokojná so svojím životom tu.
